import { WZ4_OPERATORS, WZ4_OPERATOR_COUNT } from "./operator-manifest.js";
import { exportExecutableJpeg } from "./exporter.js";
import { TUTORIALS } from "./tutorials.js";
import { BUILTIN_DEMOS } from "./demos.js";

const $ = (s, root = document) => root.querySelector(s);
const $$ = (s, root = document) => [...root.querySelectorAll(s)];

const coreOperatorCatalog = [
  { category: "GENERATORS", items: [["Primitive", "◇", "scene"], ["Text", "T", "scene"], ["Grid Array", "▦", "scene"], ["Fractal", "✣", "scene"], ["Multiply", "×", "scene"]] },
  { category: "MODIFIERS", items: [["Transform", "⌖", "scene"], ["Twist", "⟲", "scene"], ["Displace", "≋", "scene"], ["Mirror", "◫", "scene"]] },
  { category: "MATERIALS", items: [["Iridescent", "◈", "material"], ["Emission", "✦", "material"], ["Glass", "♢", "material"], ["Normal Map", "↗", "material"]] },
  { category: "TEXTURE LAB", items: [["Animated Noise", "≈", "texture"], ["Domain Warp", "⌁", "texture"], ["Kaleidoscope", "✣", "texture"], ["Palette Map", "◈", "texture"], ["Texture Output", "▣", "texture"]] },
  { category: "SIGNALS", items: [["Beat", "⌁", "signal"], ["Sine", "∿", "signal"], ["Envelope", "⌁", "signal"], ["Noise", "⌇", "signal"]] },
  { category: "AUDIO", items: [["Drum Machine", "◫", "audio"], ["Bass Synth", "≋", "audio"], ["Lowpass", "∿", "audio"], ["Delay", "↻", "audio"]] },
  { category: "POST PROCESS", items: [["Bloom", "✺", "post"], ["Chromatic", "◉", "post"], ["Vignette", "◌", "post"], ["Film Grain", "⠿", "post"]] }
];
const operatorById=new Map(WZ4_OPERATORS.map(op=>[op.id,op]));
const familyStyle={"Bitmap & Texture":["▧","texture"],"Mesh & Geometry":["◇","scene"],"Particles & Simulation":["✣","post"],"Material & Shading":["◈","material"],"Scene & Render":["◉","scene"],"Animation & Control":["⌁","signal"],"Audio Analysis":["♪","audio"],"Utility & Project FX":["⌘","post"]};
const compatibilityCatalog=[...new Set(WZ4_OPERATORS.map(op=>op.family))].map(family=>({category:`WZ4 • ${family.toUpperCase()}`,compat:true,items:WZ4_OPERATORS.filter(op=>op.family===family).map(op=>[op.name,...familyStyle[family],"schema",op.id])}));
const operatorCatalog=[...coreOperatorCatalog,...compatibilityCatalog];
const operatorDocs={
  Primitive:{summary:"Creates the base signed-distance geometry used by the WebGL scene.",usage:"Choose the shape, then adjust scale and detail. Connect it through modifiers and a material before the scene output.",input:"Signal modulation",output:"Geometry"},Text:{summary:"Renders animated typography over the WebGL scene.",usage:"Enter text, position and style it, then bind size, rotation, position or wave to a modulation source.",input:"Signals / events",output:"Scene overlay"},"Grid Array":{summary:"Repeats geometry into a rhythmic grid-like arrangement.",usage:"Set columns and spacing, then animate offset from Beat or Bar for patterned motion.",input:"Geometry",output:"Repeated geometry"},Fractal:{summary:"Adds recursive procedural complexity to a shape or texture.",usage:"Increase iterations carefully, then tune complexity and scale. Bind complexity to an envelope for organic growth.",input:"Geometry / texture",output:"Fractal field"},Multiply:{summary:"Creates multiple animated copies of incoming geometry.",usage:"Set copy count and spread, then bind Spread or Spin to Bar and Envelope sources for breathing object formations.",input:"Geometry",output:"Multiplied geometry"},
  Transform:{summary:"Changes scale, rotation and depth of incoming geometry.",usage:"Place it after a generator. Bind rotation to Sine or Bar for continuous motion.",input:"Geometry",output:"Transformed geometry"},Twist:{summary:"Deforms geometry around its axis.",usage:"Connect geometry into it, tune Amount, and bind the value to Beat or Half-beat for rhythmic deformation.",input:"Geometry + signal",output:"Deformed geometry"},Displace:{summary:"Moves the surface using procedural noise.",usage:"Tune amount and frequency; small values add detail while large values create liquid motion.",input:"Geometry / texture",output:"Displaced field"},Mirror:{summary:"Folds geometry across multiple symmetry axes.",usage:"Change axes and angle to build kaleidoscopic forms. Animate angle slowly with Sine.",input:"Geometry",output:"Mirrored geometry"},
  Iridescent:{summary:"Applies reflective, color-shifting material shading.",usage:"Tune metallic and roughness, then bind Pulse or Roughness to audio signals for reactive highlights.",input:"Geometry + texture",output:"Shaded material"},Emission:{summary:"Adds self-lit color and glow.",usage:"Raise Glow and Intensity for neon surfaces; bind Pulse to Beat for flashes.",input:"Geometry / color",output:"Emissive material"},Glass:{summary:"Creates a glossy refractive-looking material.",usage:"Use low roughness for sharp glass and increase refraction mix for stronger procedural distortion.",input:"Geometry + texture",output:"Glass material"},"Normal Map":{summary:"Uses procedural texture contrast as surface detail.",usage:"Adjust strength and scale after a texture generator, then blend it into a material.",input:"Texture",output:"Surface normals"},
  "Animated Noise":{summary:"Generates time-varying multi-octave procedural noise.",usage:"Frequency controls detail, Speed controls motion, and Contrast sharpens the result.",input:"Time / signal",output:"Texture"},"Domain Warp":{summary:"Distorts texture coordinates with a second noise field.",usage:"Place it after noise. Increase Amount for liquid curls and animate Speed for flowing motion.",input:"Texture",output:"Warped texture"},Kaleidoscope:{summary:"Folds a texture into radial symmetry.",usage:"Choose segment count, then animate rotation or warp to create evolving patterns.",input:"Texture",output:"Folded texture"},"Palette Map":{summary:"Maps procedural values between the project colors.",usage:"Tune contrast and material mix; edit Base and Accent colors to define the palette.",input:"Monochrome texture",output:"Color texture"},"Texture Output":{summary:"Publishes the texture graph to scene materials.",usage:"Connect the final texture here, then adjust material mix to control its influence on the scene.",input:"Texture",output:"Material texture"},
  Beat:{summary:"Produces a BPM-synchronized pulse.",usage:"Bind any property to Beat for quarter-note movement or Half-beat for a slower alternating pulse.",input:"Transport BPM",output:"0–1 signal"},Sine:{summary:"Produces smooth periodic modulation.",usage:"Use it for camera motion, rotation, color treatment or any value that should move continuously.",input:"Time",output:"Bipolar signal"},Envelope:{summary:"Produces a fast attack and decaying pulse each beat.",usage:"Ideal for bass cutoff, bloom hits, roughness and scale punches.",input:"Beat / event",output:"Decay envelope"},Noise:{summary:"Produces stepped pseudo-random modulation.",usage:"Use a shallow depth for flicker or larger depth for glitchy, unpredictable variation.",input:"Time",output:"Random signal"},
  "Drum Machine":{summary:"Schedules procedural kick, snare and hi-hat voices with WebAudio.",usage:"Adjust decay and drive, then enable sound. The HAHAHACK score changes its pattern across six acts.",input:"Beat clock",output:"Audio"},"Bass Synth":{summary:"Plays a filtered sawtooth bass sequence.",usage:"Tune cutoff, decay and drive. Envelope-bound cutoff creates the classic rhythmic filter movement.",input:"Notes + beat",output:"Audio"},Lowpass:{summary:"Removes high frequencies from incoming audio.",usage:"Lower Cutoff for darker sound; increase Resonance for a sharper filter peak.",input:"Audio",output:"Filtered audio"},Delay:{summary:"Adds repeating echoes to audio.",usage:"Control feedback carefully, then set mix. Bind mix to Act Event for section transitions.",input:"Audio",output:"Echoed audio"},"Audio Output":{summary:"Controls final WebAudio level sent to the speakers.",usage:"Set Volume or modulate it gently. Click SOUND OFF once to unlock browser audio.",input:"Audio",output:"Speakers"},
  Bloom:{summary:"Adds glow around bright pixels.",usage:"Use moderate intensity for polish or bind it to Beat for flashes and finales.",input:"Scene color",output:"Post-processed color"},Chromatic:{summary:"Separates color channels for a glitch-like edge effect.",usage:"Keep Amount subtle, or trigger larger values from Act Event during transitions.",input:"Scene color",output:"Chromatic color"},Vignette:{summary:"Darkens the frame edges.",usage:"Increase Amount to focus attention toward the center; combine with Exposure to balance brightness.",input:"Scene color",output:"Graded color"},"Film Grain":{summary:"Adds high-frequency texture to the final image.",usage:"Use a small amount for cinematic texture or Noise modulation for harsher glitch aesthetics.",input:"Scene color",output:"Grained color"},"Color Grade":{summary:"Adjusts final exposure and contrast.",usage:"Place near the end of the post chain and use it to balance each visual act.",input:"Scene color",output:"Graded color"},
  Camera:{summary:"Controls the orbiting WebGL camera.",usage:"Adjust distance, yaw and pitch, or bind them to Sine and Bar for automated camera paths.",input:"Transform / signal",output:"View"},Output:{summary:"Combines the scene, camera, text and post-processing into the final demo.",usage:"Show automation blends the scripted HAHAHACK acts with manual parameters. Set it to zero for full manual control.",input:"Scene + camera",output:"Final frame"},"Scene Input":{summary:"Feeds the rendered 3D scene into the post-processing graph.",usage:"Start the post chain here, then connect Bloom, grading and Vignette before Final Image.",input:"Rendered scene",output:"HDR color"}
};

const defaultNodes = [
  { id:"TXT_00", name:"Hahahack Titles", type:"TEXT OPERATOR", kind:"Text", x:10,y:4,color:"#ff3b8d", value:"6 WORLDS", enabled:true,params:{text:"HAHAHACK",textColor:"#fff3b0",textSize:42,textX:50,textY:16,textRotation:-1,textWave:.28,sequence:["ORBITAL CATHEDRAL","CRYSTAL RECURSION","SOLAR ORGANISM","MONOLITH MULTIPLY","ACID FRACTAL","HAHAHACK // TOTAL CHAOS"]},bindings:{textWave:{source:"bar",amount:.16}} },
  { id:"TXT_BRAND", name:"Hahahack Badge", type:"TEXT OPERATOR", kind:"Text", x:445,y:86,color:"#ff5a36", value:"ALWAYS ON", enabled:true,params:{text:"HAHAHACK",textColor:"#ff7655",textSize:16,textX:92,textY:89,textRotation:0,textWave:0,badge:true} },
  { id:"SIG_01", name:"Beat Pulse", type:"SIGNAL OPERATOR", kind:"Beat", x:145,y:4,color:"#55d887", value:"264 BPM", enabled:true },
  { id:"GEO_02", name:"Shape Source", type:"GEOMETRY OPERATOR", kind:"Primitive", x:280,y:4,color:"#5da7ff", value:"6 WORLDS", enabled:true },
  { id:"FRA_03", name:"Recursive Fractal", type:"GEOMETRY OPERATOR", kind:"Fractal", x:415,y:4,color:"#9b7bff", value:"3 LEVELS", enabled:true,bindings:{texWarp:{source:"envelope",amount:.2}} },
  { id:"MUL_04", name:"Object Multiply", type:"GEOMETRY OPERATOR", kind:"Multiply", x:550,y:4,color:"#25c9cd", value:"12 COPIES", enabled:true,bindings:{multiplySpread:{source:"bar",amount:.18}} },
  { id:"ARR_05", name:"Infinite Array", type:"GEOMETRY OPERATOR", kind:"Grid Array", x:695,y:4,color:"#5da7ff", value:"POLAR + GRID", enabled:true },
  { id:"MOD_03", name:"Act Morph", type:"MODIFIER OPERATOR", kind:"Twist", x:10,y:86,color:"#25c9cd", value:"6 × 5 SEC", enabled:true,bindings:{twist:{source:"half",amount:.18}} },
  { id:"MAT_04", name:"Candy Chrome", type:"MATERIAL OPERATOR", kind:"Iridescent", x:155,y:86,color:"#ff6d42", value:"AUDIO REACTIVE", enabled:true,bindings:{pulse:{source:"beat",amount:.32},roughness:{source:"envelope",amount:-.12}} },
  { id:"CAM_06", name:"Auto Orbit", type:"SCENE OPERATOR", kind:"Camera", x:300,y:86,color:"#f1b85b", value:"60 SEC PATH", enabled:true },
  { id:"OUT_07", name:"Hahahack Output", type:"OUTPUT OPERATOR", kind:"Output", x:600,y:86,color:"#ff5a36", value:"00:30 LOOP", enabled:true }
];
const defaultConnections = [["TXT_00","OUT_07"],["TXT_BRAND","OUT_07"],["SIG_01","MOD_03"],["GEO_02","FRA_03"],["FRA_03","MUL_04"],["MUL_04","ARR_05"],["ARR_05","MOD_03"],["MOD_03","MAT_04"],["MAT_04","OUT_07"],["CAM_06","OUT_07"]];
const defaultPostNodes=[
  {id:"POST_01",name:"Scene Color",type:"RENDER INPUT",kind:"Scene Input",x:35,y:58,color:"#5da7ff",value:"HDR",enabled:true},
  {id:"POST_02",name:"Hot Bloom",type:"POST FX OPERATOR",kind:"Bloom",x:195,y:34,color:"#9b7bff",value:"BEAT BOUND",enabled:true,bindings:{bloom:{source:"beat",amount:.18}}},
  {id:"POST_03",name:"Color Grade",type:"POST FX OPERATOR",kind:"Color Grade",x:355,y:62,color:"#ff6d42",value:"FILMIC",enabled:true},
  {id:"POST_04",name:"Vignette",type:"POST FX OPERATOR",kind:"Vignette",x:515,y:40,color:"#9b7bff",value:"0.17",enabled:true},
  {id:"POST_05",name:"Final Image",type:"RENDER OUTPUT",kind:"Output",x:675,y:68,color:"#55d887",value:"DISPLAY",enabled:true}
];
const defaultPostConnections=[["POST_01","POST_02"],["POST_02","POST_03"],["POST_03","POST_04"],["POST_04","POST_05"]];
const defaultAudioNodes=[
  {id:"AUDIO_01",name:"Beat Clock",type:"AUDIO CONTROL",kind:"Beat",x:35,y:58,color:"#55d887",value:"264 BPM",enabled:true},
  {id:"AUDIO_02",name:"Drum Machine",type:"AUDIO OPERATOR",kind:"Drum Machine",x:195,y:34,color:"#55d887",value:"16 STEPS",enabled:true},
  {id:"AUDIO_03",name:"Demo Bass",type:"AUDIO OPERATOR",kind:"Bass Synth",x:355,y:62,color:"#25c9cd",value:"C MINOR",enabled:true,bindings:{audioCutoff:{source:"envelope",amount:.42}}},
  {id:"AUDIO_04",name:"Lowpass",type:"AUDIO OPERATOR",kind:"Lowpass",x:515,y:40,color:"#f1b85b",value:"920 HZ",enabled:true},
  {id:"AUDIO_05",name:"Master Output",type:"AUDIO OUTPUT",kind:"Audio Output",x:675,y:68,color:"#ff6d42",value:"-7.5 DB",enabled:true}
];
const defaultAudioConnections=[["AUDIO_01","AUDIO_02"],["AUDIO_01","AUDIO_03"],["AUDIO_02","AUDIO_04"],["AUDIO_03","AUDIO_04"],["AUDIO_04","AUDIO_05"]];
const defaultTextureNodes = [
  { id:"TEX_01", name:"Flow Noise", type:"TEXTURE GENERATOR", kind:"Animated Noise", x:35,y:54,color:"#25c9cd",value:"5 OCT",enabled:true },
  { id:"TEX_02", name:"Liquid Warp", type:"TEXTURE MODIFIER", kind:"Domain Warp", x:195,y:32,color:"#5da7ff",value:"1.15 AMT",enabled:true },
  { id:"TEX_03", name:"Radial Fold", type:"TEXTURE MODIFIER", kind:"Kaleidoscope", x:355,y:60,color:"#9b7bff",value:"6 SIDES",enabled:true },
  { id:"TEX_04", name:"Neon Palette", type:"TEXTURE COLOR", kind:"Palette Map", x:515,y:38,color:"#ff6d42",value:"2 COLORS",enabled:true },
  { id:"TEX_05", name:"Material Map", type:"TEXTURE OUTPUT", kind:"Texture Output", x:675,y:72,color:"#55d887",value:"ANIMATED",enabled:true }
];
const defaultTextureConnections=[["TEX_01","TEX_02"],["TEX_02","TEX_03"],["TEX_03","TEX_04"],["TEX_04","TEX_05"]];
const defaults = { shapeMode:0,color:"#ff3b8d", accent:"#5cf5ff", metallic:0.91, roughness:0.18, twist:1.4, bloom:0.92, vignette:.2, pulse:0.72, scale:1, exposure:1.2, texScale:4.8, texSpeed:.52, texWarp:1.65, texContrast:1.8, texKaleido:7, texMix:.86,multiplyCount:8,multiplySpread:1.25, audioCutoff:1320, audioDecay:0.3, audioDelay:0.22, audioDrive:0.64,showMix:1 };
const DEFAULT_SCENE_VERSION=7;
let state = { nodes: structuredClone(defaultNodes), connections: structuredClone(defaultConnections),textureNodes:structuredClone(defaultTextureNodes),textureConnections:structuredClone(defaultTextureConnections),postNodes:structuredClone(defaultPostNodes),postConnections:structuredClone(defaultPostConnections),audioNodes:structuredClone(defaultAudioNodes),audioConnections:structuredClone(defaultAudioConnections),graphMode:"scene",params:{...defaults}, audio:{enabled:false,volume:.42}, selected:"TXT_00", playing:true, looping:true, duration:30, time:0, bpm:264, zoom:1, history:[],showcase:true,sceneVersion:DEFAULT_SCENE_VERSION };
let glState = null, lastFrame = performance.now(), fpsSmooth = 60, orbit = { yaw:0.15, pitch:0.1, distance:4.5 }, draggingNode = null, connectingPort = null;
const audioEngine = { ctx:null, master:null, analyser:null, noise:null, nextTime:0, step:0, spectrum:null };
let activeTutorial=null,tutorialStep=0,tutorialNavTime=0,lastExternalEvent=-99;

function renderLibrary(filter="") {
  $("#operatorList").innerHTML = operatorCatalog.map(group => {
    const items = group.items.filter(i => i[0].toLowerCase().includes(filter.toLowerCase()));
    if (!items.length) return "";
    return `<section class="op-category ${group.compat?"compat-category":""}"><button><span>⌄ ${group.category}</span><span>${items.length}</span></button><div class="op-items" ${group.compat&&!filter?"hidden":""}>${items.map(i=>{const spec=i[4]?operatorById.get(i[4]):null;return `<button class="op" draggable="false" data-drag="operator" data-kind="${i[0]}" ${i[4]?`data-opid="${i[4]}"`:""} title="${spec?`${spec.output} ${spec.symbol}(${spec.inputs}) · ${spec.module}`:i[0]}"><span class="op-icon ${i[2]}">${i[1]}</span><span>${i[0]}</span>${i[3]?`<small>${i[3]}</small>`:""}</button>`}).join("")}</div></section>`;
  }).join("");
  $$(".op", $("#operatorList")).forEach(bindOperatorCard);
  $$(".op-category>button").forEach(b=>b.onclick=()=>b.nextElementSibling.hidden=!b.nextElementSibling.hidden);
  $("#operatorCount").textContent=`${WZ4_OPERATOR_COUNT} WZ4 OPS`;
}

function currentNodes(){return state.graphMode==="textures"?state.textureNodes:state.graphMode==="post"?state.postNodes:state.graphMode==="audio"?state.audioNodes:state.nodes;}
function currentConnections(){return state.graphMode==="textures"?state.textureConnections:state.graphMode==="post"?state.postConnections:state.graphMode==="audio"?state.audioConnections:state.connections;}
function allNodes(){return [...state.nodes,...state.textureNodes,...state.postNodes,...state.audioNodes];}
function nodeMarkup(n) { return `<div class="node ${n.id===state.selected?"selected":""}" data-id="${n.id}" style="left:${n.x}px;top:${n.y}px;--node-color:${n.color};opacity:${n.enabled?1:.45}"><i class="port in" title="Input · drag to connect"></i><i class="port out" title="Output · drag to connect"></i><button class="node-info" type="button" aria-label="About ${n.name}" title="How to use ${n.name}">(i)</button><div class="node-head"><i></i><span>${n.name.toUpperCase()}</span></div><div class="node-preview">${n.kind.toUpperCase()}</div><div class="node-meta"><span>${n.id}</span><span>${n.value}</span></div></div>`; }
function showNodeHelp(node){const doc=operatorDocs[node.kind]||{summary:node.compat?"This original Werkkzeug4 operator is indexed from its public schema.":"A web-native operator in the current graph.",usage:node.compat?"Connect it according to its declared inputs and output. Its browser runtime still needs to be ported before it can affect rendering.":"Connect its input and output ports, then edit and modulate its inspector properties.",input:node.compat?.inputs||"Graph input",output:node.compat?.output||"Graph output"};$("#nodeHelpType").textContent=node.compat?"WZ4 SCHEMA GUIDE":"WEB-NATIVE OPERATOR GUIDE";$("#nodeHelpTitle").textContent=node.name;$("#nodeHelpSummary").textContent=doc.summary;$("#nodeHelpUsage").textContent=doc.usage;const io=$("#nodeHelpIO");io.replaceChildren();for(const [label,value] of [["INPUT",doc.input],["OUTPUT",doc.output]]){const item=document.createElement("div"),heading=document.createElement("b");heading.textContent=label;item.append(heading,document.createTextNode(String(value)));io.append(item);}$("#nodeHelpModal").hidden=false;}
function setCurrentConnections(connections){
  if(state.graphMode==="textures")state.textureConnections=connections;
  else if(state.graphMode==="post")state.postConnections=connections;
  else if(state.graphMode==="audio")state.audioConnections=connections;
  else state.connections=connections;
}
function constrainGraphNodes(){
  const canvas=$("#graphCanvas");if(!canvas)return;
  $$(".node",canvas).forEach(element=>{const node=currentNodes().find(item=>item.id===element.dataset.id);if(!node)return;const maxX=Math.max(0,canvas.clientWidth/state.zoom-element.offsetWidth),maxY=Math.max(0,canvas.clientHeight/state.zoom-element.offsetHeight);node.x=Math.max(0,Math.min(maxX,node.x));node.y=Math.max(0,Math.min(maxY,node.y));element.style.left=`${node.x}px`;element.style.top=`${node.y}px`;});
}
function finishConnection(event){
  if(!connectingPort||event.pointerId!==connectingPort.pointerId)return;
  const source=connectingPort,target=event.type==="pointercancel"?null:document.elementFromPoint(event.clientX,event.clientY)?.closest(".port");
  const targetNode=target?.closest(".node")?.dataset.id,targetDirection=target?.classList.contains("out")?"out":"in";
  if(target&&targetNode&&targetNode!==source.nodeId&&targetDirection!==source.direction){
    const from=source.direction==="out"?source.nodeId:targetNode,to=source.direction==="in"?source.nodeId:targetNode;
    const existing=currentConnections(),duplicate=existing.some(([a,b])=>a===from&&b===to);
    if(!duplicate){setCurrentConnections([...existing.filter(([,b])=>b!==to),[from,to]]);autosave();}
  }
  window.removeEventListener("pointermove",moveConnection);window.removeEventListener("pointerup",finishConnection);window.removeEventListener("pointercancel",finishConnection);
  $("#graphCanvas").classList.remove("connecting");connectingPort=null;drawWires();
}
function moveConnection(event){if(!connectingPort||event.pointerId!==connectingPort.pointerId)return;connectingPort.clientX=event.clientX;connectingPort.clientY=event.clientY;drawWires();}
function startConnection(event,nodeId,direction){
  if(event.button!==0)return;event.preventDefault();event.stopPropagation();connectingPort={nodeId,direction,pointerId:event.pointerId,clientX:event.clientX,clientY:event.clientY};
  $("#graphCanvas").classList.add("connecting");window.addEventListener("pointermove",moveConnection);window.addEventListener("pointerup",finishConnection);window.addEventListener("pointercancel",finishConnection);drawWires();
}
function renderGraph() {
  $("#nodes").innerHTML = currentNodes().map(nodeMarkup).join("");
  $$(".node").forEach(el => {
    el.onpointerdown = e => {
      selectNode(el.dataset.id);
      if(e.button!==0||e.target.closest(".port,.node-info"))return;
      e.preventDefault();const n=currentNodes().find(x=>x.id===el.dataset.id),pointerId=e.pointerId,canvas=$("#graphCanvas");draggingNode={n,startX:n.x,startY:n.y,pointerX:e.clientX,pointerY:e.clientY,el};el.classList.add("dragging");
      const move=event=>{if(!draggingNode||event.pointerId!==pointerId)return;const maxX=Math.max(0,canvas.clientWidth/state.zoom-el.offsetWidth),maxY=Math.max(0,canvas.clientHeight/state.zoom-el.offsetHeight);draggingNode.n.x=Math.max(0,Math.min(maxX,draggingNode.startX+(event.clientX-draggingNode.pointerX)/state.zoom));draggingNode.n.y=Math.max(0,Math.min(maxY,draggingNode.startY+(event.clientY-draggingNode.pointerY)/state.zoom));el.style.left=draggingNode.n.x+"px";el.style.top=draggingNode.n.y+"px";drawWires();};
      const up=event=>{if(!draggingNode||event.pointerId!==pointerId)return;el.classList.remove("dragging");draggingNode=null;window.removeEventListener("pointermove",move);window.removeEventListener("pointerup",up);window.removeEventListener("pointercancel",up);autosave();};window.addEventListener("pointermove",move);window.addEventListener("pointerup",up);window.addEventListener("pointercancel",up);
    };
    $$(".port",el).forEach(port=>port.onpointerdown=event=>startConnection(event,el.dataset.id,port.classList.contains("out")?"out":"in"));
    const info=$(".node-info",el);info.onpointerdown=event=>event.stopPropagation();info.onclick=event=>{event.stopPropagation();const node=currentNodes().find(item=>item.id===el.dataset.id);if(node)showNodeHelp(node);};
  });
  requestAnimationFrame(()=>{constrainGraphNodes();drawWires();});
}
function drawWires() {
  const area=$("#graphCanvas").getBoundingClientRect();
  const paths=currentConnections().map(([a,b],i)=>{
    const from=$(`.node[data-id="${a}"] .port.out`), to=$(`.node[data-id="${b}"] .port.in`); if(!from||!to)return"";
    const ar=from.getBoundingClientRect(), br=to.getBoundingClientRect(), x1=ar.left-area.left+4,y1=ar.top-area.top+4,x2=br.left-area.left+4,y2=br.top-area.top+4, d=Math.max(35,Math.abs(x2-x1)*.48);
    return `<path class="wire ${i>2?"hot":""}" data-wire="${i}" d="M${x1},${y1} C${x1+d},${y1} ${x2-d},${y2} ${x2},${y2}"/>`;
  });
  if(connectingPort){const port=$(`.node[data-id="${connectingPort.nodeId}"] .port.${connectingPort.direction}`),rect=port?.getBoundingClientRect();if(rect){const px=rect.left-area.left+4,py=rect.top-area.top+4,cx=connectingPort.clientX-area.left,cy=connectingPort.clientY-area.top,x1=connectingPort.direction==="out"?px:cx,y1=connectingPort.direction==="out"?py:cy,x2=connectingPort.direction==="out"?cx:px,y2=connectingPort.direction==="out"?cy:py,d=Math.max(35,Math.abs(x2-x1)*.48);paths.push(`<path class="wire preview" d="M${x1},${y1} C${x1+d},${y1} ${x2-d},${y2} ${x2},${y2}"/>`);}}
  $("#wires").innerHTML=paths.join("");
  $$('[data-wire]',$("#wires")).forEach(path=>path.ondblclick=event=>{event.stopPropagation();const index=Number(path.dataset.wire),next=currentConnections().filter((_,i)=>i!==index);setCurrentConnections(next);drawWires();autosave();});
}
function selectNode(id){state.selected=id;$$('.node').forEach(node=>node.classList.toggle('selected',node.dataset.id===id));renderInspector();}

const paramDefinitions = {
  Primitive:[["Shape","shapeMode",0,3,1],["Scale","scale",.4,2,.01],["Detail","roughness",0,1,.01]],
  Text:[["Size","textSize",12,180,1,64],["Position X","textX",0,100,1,50],["Position Y","textY",0,100,1,50],["Rotation","textRotation",-180,180,1,0],["Wave","textWave",0,1,.01,.25]],
  "Grid Array":[["Columns","texKaleido",2,16,1],["Spacing","scale",.4,2,.01],["Offset","twist",0,3,.01]],Fractal:[["Iterations","texKaleido",2,16,1],["Complexity","texWarp",0,3,.01],["Scale","texScale",.5,10,.05]],Multiply:[["Copies","multiplyCount",1,16,1,8],["Spread","multiplySpread",.2,3,.01,1.25],["Spin","twist",0,3,.01]],
  Transform:[["Scale","scale",.4,2,.01],["Rotation","twist",0,3,.01],["Depth","exposure",.2,2,.01]],Twist:[["Amount","twist",0,3,.01],["Scale","scale",.4,2,.01],["Pulse","pulse",0,1,.01]],Displace:[["Amount","texWarp",0,3,.01],["Frequency","texScale",.5,10,.05],["Speed","texSpeed",-.5,2,.01]],Mirror:[["Axes","texKaleido",2,16,1],["Angle","twist",0,3,.01]],
  Iridescent:[["Metallic","metallic",0,1,.01],["Roughness","roughness",0,1,.01],["Pulse","pulse",0,1,.01],["Exposure","exposure",.2,2,.01]],Emission:[["Glow","bloom",0,1.5,.01],["Intensity","exposure",.2,2,.01],["Pulse","pulse",0,1,.01]],Glass:[["Roughness","roughness",0,1,.01],["Refraction","texMix",0,1,.01],["Exposure","exposure",.2,2,.01]],"Normal Map":[["Strength","texContrast",.4,3,.01],["Scale","texScale",.5,10,.05],["Mix","texMix",0,1,.01]],
  "Animated Noise":[["Frequency","texScale",.5,10,.05],["Speed","texSpeed",-.5,2,.01],["Contrast","texContrast",.4,3,.01]],"Domain Warp":[["Amount","texWarp",0,3,.01],["Frequency","texScale",.5,10,.05],["Speed","texSpeed",-.5,2,.01]],Kaleidoscope:[["Segments","texKaleido",2,16,1],["Rotation","texSpeed",-.5,2,.01],["Warp","texWarp",0,3,.01]],"Palette Map":[["Contrast","texContrast",.4,3,.01],["Material mix","texMix",0,1,.01],["Speed","texSpeed",-.5,2,.01]],"Texture Output":[["Material mix","texMix",0,1,.01],["Scale","texScale",.5,10,.05]],
  Beat:[["Amplitude","pulse",0,1,.01],["Rate","twist",0,3,.01]],Sine:[["Amplitude","pulse",0,1,.01],["Frequency","texSpeed",-.5,2,.01],["Phase","twist",0,3,.01]],Envelope:[["Attack","audioDrive",0,1,.01],["Decay","audioDecay",.08,.8,.01],["Amount","pulse",0,1,.01]],Noise:[["Amount","texWarp",0,3,.01],["Frequency","texScale",.5,10,.05]],
  "Drum Machine":[["Decay","audioDecay",.08,.8,.01],["Drive","audioDrive",0,1,.01]],"Bass Synth":[["Cutoff","audioCutoff",120,4800,10],["Decay","audioDecay",.08,.8,.01],["Drive","audioDrive",0,1,.01]],Lowpass:[["Cutoff","audioCutoff",120,4800,10],["Resonance","audioDrive",0,1,.01]],Delay:[["Feedback","audioDelay",0,.75,.01],["Mix","audioDrive",0,1,.01]],"Audio Output":[["Volume","masterVolume",0,1,.01,.42]],
  Bloom:[["Intensity","bloom",0,1.5,.01],["Exposure","exposure",.2,2,.01]],Chromatic:[["Amount","texMix",0,1,.01],["Speed","texSpeed",-.5,2,.01]],Vignette:[["Amount","vignette",0,.8,.01],["Exposure","exposure",.2,2,.01]],"Film Grain":[["Amount","roughness",0,1,.01],["Exposure","exposure",.2,2,.01]],"Color Grade":[["Exposure","exposure",.2,2,.01],["Contrast","texContrast",.4,3,.01]],
  Camera:[["Distance","cameraDistance",2.5,8,.05,4.5],["Yaw","cameraYaw",-3.14,3.14,.01,.15],["Pitch","cameraPitch",-1.2,1.2,.01,.1]],Output:[["Show automation","showMix",0,1,.01],["Exposure","exposure",.2,2,.01],["Bloom","bloom",0,1.5,.01]],"Scene Input":[["Exposure","exposure",.2,2,.01]]
};
const sectionTitles={Text:"TEXT & LAYOUT",Primitive:"GEOMETRY","Grid Array":"GEOMETRY",Fractal:"GEOMETRY",Multiply:"GEOMETRY",Transform:"TRANSFORM",Twist:"DEFORMATION",Displace:"DEFORMATION",Mirror:"SYMMETRY",Iridescent:"MATERIAL",Emission:"MATERIAL",Glass:"MATERIAL","Normal Map":"MATERIAL",Beat:"SIGNAL",Sine:"SIGNAL",Envelope:"SIGNAL",Noise:"SIGNAL","Drum Machine":"SYNTHESIS","Bass Synth":"SYNTHESIS",Lowpass:"FILTER",Delay:"EFFECT",Bloom:"POST PROCESS",Chromatic:"POST PROCESS",Vignette:"POST PROCESS","Film Grain":"POST PROCESS"};
const bindingSources=[["none","NONE"],["beat","BEAT"],["half","HALF-BEAT"],["bar","BAR"],["sine","SINE"],["envelope","ENVELOPE"],["noise","NOISE"],["act","ACT EVENT"],["event","EVENT"]];
function sourceSignal(source){const beatPhase=state.time*state.bpm/60,motionTime=state.showcase?state.time*2:state.time,phase=value=>value-Math.floor(value);if(source==="beat")return .5+.5*Math.sin(beatPhase*Math.PI*2);if(source==="half")return .5+.5*Math.sin(beatPhase*Math.PI);if(source==="bar")return .5+.5*Math.sin(beatPhase*Math.PI/2);if(source==="sine")return Math.sin(motionTime*Math.PI*.5);if(source==="envelope")return Math.exp(-phase(beatPhase)*6);if(source==="noise")return Math.sin(Math.floor(motionTime*12.5)*91.73)*.5+.5;if(source==="act")return Math.exp(-(state.time%(state.showcase?5:10))*5);if(source==="event")return Math.exp(-(performance.now()/1000-lastExternalEvent)*8);return 0;}
function bindingFor(node,key){return node.bindings?.[key]||{source:"none",amount:.35};}
function boundValue(node,key,base,min,max){const binding=bindingFor(node,key);if(binding.source==="none")return base;return Math.max(min,Math.min(max,base+sourceSignal(binding.source)*(binding.amount??.35)*(max-min)*.5));}
function applyParameterBindings(params){const result={...params};for(const node of allNodes()){if(!node.enabled||node.compat)continue;for(const [,key,min,max,,fallback=0] of paramDefinitions[node.kind]||[]){if(!(key in result))continue;result[key]=boundValue(node,key,result[key]??fallback,min,max);}}return result;}
function bindingMarkup(node,key){const binding=bindingFor(node,key),options=bindingSources.map(([value,label])=>`<option value="${value}" ${binding.source===value?"selected":""}>${label}</option>`).join("");return `<div class="mod-row ${binding.source==="none"?"inactive":""}" data-binding-row="${key}"><select data-bind-source="${key}" aria-label="${key} modulation source">${options}</select><input type="range" data-bind-amount="${key}" min="-1" max="1" step=".01" value="${binding.amount??.35}" aria-label="${key} modulation depth"><span class="mod-value" data-bind-value="${key}">${binding.source==="none"?"OFF":`${Math.round((binding.amount??.35)*100)}%`}</span></div>`;}
function updateBindingReadouts(){const node=allNodes().find(item=>item.id===state.selected);if(!node)return;$$('[data-binding-row]').forEach(row=>{const key=row.dataset.bindingRow,binding=bindingFor(node,key),readout=$(`[data-bind-value="${key}"]`,row);if(readout)readout.textContent=binding.source==="none"?"OFF":`${sourceSignal(binding.source)>=0?"+":""}${sourceSignal(binding.source).toFixed(2)}`;});}
function boundSpecial(kind,key,base){const node=allNodes().find(item=>item.kind===kind&&item.enabled),definition=paramDefinitions[kind]?.find(([,candidate])=>candidate===key);return node&&definition?boundValue(node,key,base,definition[2],definition[3]):base;}
function parameterValue(node,key,fallback){if(key==="masterVolume")return state.audio.volume;if(key==="cameraDistance")return orbit.distance;if(key==="cameraYaw")return orbit.yaw;if(key==="cameraPitch")return orbit.pitch;if(key in state.params)return state.params[key];return node.params?.[key]??fallback;}
function setParameterValue(node,key,value){node.params??={};node.params[key]=value;if(key in state.params)state.params[key]=value;else if(key==="masterVolume"){state.audio.volume=value;$("#masterVolume").value=value;if(state.audio.enabled&&state.playing)setAudioGain(value);}else if(key==="cameraDistance")orbit.distance=value;else if(key==="cameraYaw")orbit.yaw=value;else if(key==="cameraPitch")orbit.pitch=value;}
const showActs=[
  {shapeMode:0,color:"#ff3b8d",accent:"#5cf5ff",twist:1.3,scale:1,bloom:.85,vignette:.16,exposure:1.18,pulse:.72,texScale:4.4,texSpeed:.42,texWarp:1.2,texContrast:1.6,texKaleido:7,texMix:.8,roughness:.2,multiplyCount:7,multiplySpread:1.5,cameraDistance:4.15},
  {shapeMode:1,color:"#6b5cff",accent:"#69ffb7",twist:2.5,scale:.86,bloom:1.15,vignette:.3,exposure:1.28,pulse:.92,texScale:7.2,texSpeed:.76,texWarp:2.2,texContrast:2.3,texKaleido:9,texMix:.94,roughness:.06,multiplyCount:12,multiplySpread:.72,cameraDistance:3.65},
  {shapeMode:2,color:"#ffb000",accent:"#ff315f",twist:.55,scale:1.12,bloom:.96,vignette:.22,exposure:1.12,pulse:1,texScale:2.5,texSpeed:.24,texWarp:2.8,texContrast:1.25,texKaleido:5,texMix:.88,roughness:.34,multiplyCount:9,multiplySpread:1.25,cameraDistance:4.05},
  {shapeMode:3,color:"#e9f7ff",accent:"#2779ff",twist:.18,scale:.92,bloom:.42,vignette:.52,exposure:.82,pulse:.3,texScale:5.1,texSpeed:.15,texWarp:.55,texContrast:2.5,texKaleido:4,texMix:.58,roughness:.28,multiplyCount:16,multiplySpread:.72,cameraDistance:5.15},
  {shapeMode:0,color:"#d5ff28",accent:"#ff23ba",twist:2.9,scale:1.08,bloom:1.2,vignette:.08,exposure:1.34,pulse:.82,texScale:8.6,texSpeed:1.15,texWarp:2.9,texContrast:2.7,texKaleido:13,texMix:1,roughness:.12,multiplyCount:11,multiplySpread:1.05,cameraDistance:2.25},
  {shapeMode:2,color:"#ffffff",accent:"#ff4d2e",twist:1.8,scale:1.22,bloom:1.35,vignette:.12,exposure:1.38,pulse:1,texScale:6.2,texSpeed:.9,texWarp:2.45,texContrast:2.1,texKaleido:11,texMix:.96,roughness:.08,multiplyCount:12,multiplySpread:1.42,cameraDistance:2.75}
];
const actNames=["ORBITAL CATHEDRAL","CRYSTAL RECURSION","SOLAR ORGANISM","MONOLITH MULTIPLY","ACID FRACTAL","TOTAL CHAOS"];
function currentActIndex(){return Math.max(0,Math.min(actNames.length-1,Math.floor((((state.time%30)+30)%30)/5)));}
function selectAct(index){if(!state.showcase)return;const next=(Number(index)+actNames.length)%actNames.length;state.time=next*5+.01;lastExternalEvent=performance.now()/1000;updateTransport();updateActUI();}
function updateActUI(){const selector=$("#actSelector"),index=currentActIndex();if(!selector)return;$("#actSwitcher").classList.toggle("disabled",!state.showcase);selector.value=String(index);$("#actCounter").textContent=state.showcase?`ACT ${index+1} / ${actNames.length}`:"TIMELINE ACTS OFF";}
function showParameters(){const result={...state.params};if(state.showcase){const index=Math.max(0,Math.min(showActs.length-1,Math.floor((((state.time%30)+30)%30)/5))),act=showActs[index]||showActs[0],mix=state.params.showMix??1,beat=.5+.5*Math.sin(state.time*Math.PI*2*(state.bpm/60));for(const [key,value] of Object.entries(act))result[key]=typeof value==="number"&&typeof state.params[key]==="number"?state.params[key]*(1-mix)+value*mix:mix>.5?value:state.params[key];result.bloom+=beat*.16*mix;result.pulse=Math.min(1,result.pulse+beat*.08*mix);result.twist+=Math.sin(state.time*1.4)*.18*mix;}return applyParameterBindings(result);}
function updateSceneOverlays(){const root=$("#sceneOverlay");if(!root)return;const texts=state.nodes.filter(node=>node.kind==="Text"&&node.enabled),defs=Object.fromEntries(paramDefinitions.Text.map(([,key,min,max,,fallback])=>[key,[min,max,fallback]])),motionTime=state.showcase?state.time*2:state.time;while(root.children.length>texts.length)root.lastElementChild.remove();texts.forEach((node,index)=>{node.params??={};const value=key=>{const [min,max,fallback]=defs[key];return boundValue(node,key,node.params[key]??fallback,min,max);},element=root.children[index]||root.appendChild(document.createElement("div")),sequence=node.params.sequence;element.className=`scene-text${node.params.badge?" scene-text-badge":""}`;element.textContent=sequence?.length?sequence[Math.floor((state.time%(state.showcase?30:60))/(state.showcase?5:10))%sequence.length]:node.params.text||"WERKKZEUG";element.style.setProperty("--text-x",`${value("textX")}%`);element.style.setProperty("--text-y",`${value("textY")}%`);element.style.setProperty("--text-size",`${value("textSize")}px`);element.style.setProperty("--text-color",node.params.textColor||state.params.accent);element.style.setProperty("--text-rotation",`${value("textRotation")+(node.params.badge?0:Math.sin(motionTime*.8)*2)}deg`);element.style.setProperty("--text-wave",`${Math.sin(motionTime*2+index)*12*value("textWave")}px`);});}
function renderInspector(){
  const n=allNodes().find(x=>x.id===state.selected)||currentNodes()[0];if(!n){$("#nodeId").textContent="—";$("#inspectorName").textContent="No operator selected";$("#inspectorType").textContent="ADD AN OPERATOR TO CONTINUE";$("#inspectorContent").innerHTML='<div class="native-runtime">THIS WORKSPACE IS EMPTY · USE ADD OPERATOR</div>';$("#deleteNode").disabled=true;return;}$("#deleteNode").disabled=false;$("#nodeId").textContent=n.id;$("#inspectorName").textContent=n.name;$("#inspectorType").textContent=n.type;$("#enableNode").classList.toggle("active",n.enabled);
  const params=paramDefinitions[n.kind]||[],textureOperator=state.textureNodes.some(x=>x.id===n.id),escapedText=String(n.params?.text||"WERKKZEUG").replace(/&/g,"&amp;").replace(/"/g,"&quot;"),textRows=n.kind==="Text"?`<label class="param-row"><span>Content</span><input class="param-text" data-text-param="text" value="${escapedText}"></label><div class="param-row"><span>Color</span><div class="color-row" style="grid-column:2/4"><input id="textColor" type="color" value="${n.params?.textColor||state.params.accent}"><input class="color-code" value="${(n.params?.textColor||state.params.accent).toUpperCase()}" readonly></div></div>`:"",accentRow=textureOperator&&!n.compat?`<div class="param-row"><span>Accent</span><div class="color-row" style="grid-column:2/4"><input id="accentColor" type="color" value="${state.params.accent}"><input class="color-code" value="${state.params.accent.toUpperCase()}" readonly></div></div>`:"";
  const showBaseColor=!n.compat&&["Primitive","Grid Array","Fractal","Iridescent","Emission","Glass","Normal Map"].includes(n.kind),runtime=n.compat?`<div class="compat-banner"><strong>SCHEMA COMPATIBLE · RUNTIME PORT REQUIRED</strong><code>${n.compat.output} ${n.compat.symbol}(${n.compat.inputs})</code>${n.compat.module} · ${n.compat.source}:${n.compat.line}</div>`:`<div class="native-runtime">WEB-NATIVE RUNTIME · LIVE OUTPUT</div>`,baseRow=showBaseColor?`<div class="param-row"><span>Base color</span><div class="color-row" style="grid-column:2/4"><input id="baseColor" type="color" value="${state.params.color}"><input class="color-code" value="${state.params.color.toUpperCase()}" readonly></div></div>`:"";
  const controls=params.map(([label,key,min,max,step,fallback=0])=>{const value=parameterValue(n,key,fallback);return `<label class="param-row"><span>${label}</span><input type="range" data-param="${key}" min="${min}" max="${max}" step="${step}" value="${value}"><input class="param-value" data-value="${key}" value="${Number(value).toFixed(step>=1?0:2)}"></label>${bindingMarkup(n,key)}`}).join(""),schema=n.compat?`<div class="param-row"><span>Output</span><div class="param-value" style="grid-column:2/4;text-align:left">${n.compat.output}</div></div><div class="param-row"><span>Inputs</span><div class="param-value" style="grid-column:2/4;text-align:left;overflow:hidden">${n.compat.inputs||"none"}</div></div>`:"";
  $("#inspectorContent").innerHTML=`${runtime}<section class="inspector-section"><button class="section-head"><span>${n.compat?"OPERATOR SCHEMA":sectionTitles[n.kind]||(textureOperator?"TEXTURE PARAMETERS":"PARAMETERS")}</span><span>⌃</span></button><div class="section-content">${textRows}${baseRow}${accentRow}${controls}${schema}</div></section>`;
  if($("#baseColor"))$("#baseColor").oninput=e=>{state.params.color=e.target.value;e.target.nextElementSibling.value=e.target.value.toUpperCase();autosave();};if($("#accentColor"))$("#accentColor").oninput=e=>{state.params.accent=e.target.value;e.target.nextElementSibling.value=e.target.value.toUpperCase();autosave();};if($("#textColor"))$("#textColor").oninput=e=>{n.params??={};n.params.textColor=e.target.value;e.target.nextElementSibling.value=e.target.value.toUpperCase();updateSceneOverlays();autosave();};if($("[data-text-param]"))$("[data-text-param]").oninput=e=>{n.params??={};n.params[e.target.dataset.textParam]=e.target.value;if(e.target.dataset.textParam==="text")delete n.params.sequence;updateSceneOverlays();autosave();};$$('[data-param]').forEach(range=>range.oninput=e=>{const key=e.target.dataset.param,value=Number(e.target.value);setParameterValue(n,key,value);$(`[data-value="${key}"]`).value=value.toFixed(Number(e.target.step)>=1?0:2);updateSceneOverlays();autosave();});$$('[data-bind-source]').forEach(select=>select.onchange=e=>{n.bindings??={};const key=e.target.dataset.bindSource,binding=n.bindings[key]||{amount:.35};binding.source=e.target.value;n.bindings[key]=binding;$(`[data-binding-row="${key}"]`).classList.toggle("inactive",binding.source==="none");autosave();});$$('[data-bind-amount]').forEach(range=>range.oninput=e=>{n.bindings??={};const key=e.target.dataset.bindAmount,binding=n.bindings[key]||{source:"none"};binding.amount=Number(e.target.value);n.bindings[key]=binding;autosave();});
}

function addNode(kind,position){
  const all=operatorCatalog.flatMap(g=>g.items), item=all.find(x=>x[0]===kind)||[kind,"◇","scene"],mode=item[2]==="texture"?"textures":item[2]==="post"?"post":item[2]==="audio"?"audio":"scene",target=mode==="textures"?state.textureNodes:mode==="post"?state.postNodes:mode==="audio"?state.audioNodes:state.nodes,idx=target.length+1;
  if(mode!==state.graphMode)switchGraphMode(mode);
  const colors={material:"#ff6d42",post:"#9b7bff",signal:"#55d887",scene:"#5da7ff",audio:"#55d887",texture:"#25c9cd"};
  const id=`OP_${String(allNodes().length+1).padStart(3,"0")}`, n={id,name:kind,type:`${item[2].toUpperCase()} OPERATOR`,kind,x:position?.x??120+(idx*47)%480,y:position?.y??45+(idx*31)%120,color:colors[item[2]],value:"LIVE",enabled:true};
  target.push(n);state.selected=id;$("#addMenu").hidden=true;renderGraph();renderInspector();updateSceneOverlays();autosave();
}
function addCompatibilityNode(spec,position){
  if(!spec)return;const mode=spec.family==="Bitmap & Texture"?"textures":spec.family==="Audio Analysis"?"audio":"scene",target=mode==="textures"?state.textureNodes:mode==="audio"?state.audioNodes:state.nodes,idx=allNodes().length+1;if(mode!==state.graphMode)switchGraphMode(mode);
  const colors={"Bitmap & Texture":"#25c9cd","Mesh & Geometry":"#5da7ff","Particles & Simulation":"#9b7bff","Material & Shading":"#ff6d42","Scene & Render":"#f1b85b","Animation & Control":"#55d887","Audio Analysis":"#55d887","Utility & Project FX":"#9b7bff"};
  const id=`WZ_${String(idx).padStart(3,"0")}`,n={id,name:spec.name,type:`${spec.output} OPERATOR`,kind:spec.symbol,x:position?.x??80+(idx*43)%540,y:position?.y??35+(idx*29)%125,color:colors[spec.family],value:"SCHEMA",enabled:true,compat:{...spec}};
  target.push(n);state.selected=id;$("#addMenu").hidden=true;renderGraph();renderInspector();autosave();
}
function removeSelected(){const id=state.selected,list=currentNodes();if(!id||!list.some(node=>node.id===id))return;const filtered=list.filter(node=>node.id!==id),withoutNode=connections=>connections.filter(connection=>!connection.includes(id));if(state.graphMode==="textures"){state.textureNodes=filtered;state.textureConnections=withoutNode(state.textureConnections);}else if(state.graphMode==="post"){state.postNodes=filtered;state.postConnections=withoutNode(state.postConnections);}else if(state.graphMode==="audio"){state.audioNodes=filtered;state.audioConnections=withoutNode(state.audioConnections);}else{state.nodes=filtered;state.connections=withoutNode(state.connections);}state.selected=currentNodes()[0]?.id||null;renderGraph();renderInspector();updateSceneOverlays();autosave();}

function switchGraphMode(mode){
  state.graphMode=["scene","textures","post","audio"].includes(mode)?mode:"scene";state.selected=currentNodes()[0]?.id;const badge=$("#textureModeBadge"),labels={textures:["TEXTURE OUTPUT","ANIMATED · GPU"],post:["POST PROCESS","LIVE · GPU"],audio:["AUDIO GRAPH","WEB AUDIO · 128 BPM"]};badge.hidden=state.graphMode==="scene";if(labels[state.graphMode]){$("span",badge).textContent=labels[state.graphMode][0];$("b",badge).textContent=labels[state.graphMode][1];}renderGraph();renderInspector();
}

function initTimeline(){
  const tracks=state.showcase?[["SHOW / ACT MORPH","#f1b85b"],["AUDIO / 6-ACT SCORE","#55d887"],["TEXT / TITLE SEQUENCE","#ff6d42"],["POST / BUILD + FINALE","#9b7bff"]]:[["CAMERA / ORBIT","#f1b85b"],["AUDIO / DEMO SYNTH","#55d887"],["MATERIAL / PULSE","#ff6d42"],["POST / BLOOM","#9b7bff"]];
  $("#trackNames").innerHTML=tracks.map(t=>`<div class="track-name" style="--track-color:${t[1]}"><i></i>${t[0]}<span>◆</span></div>`).join("");
  $("#ruler").innerHTML=Array.from({length:13},(_,i)=>`<span>${String(state.showcase?Math.round(i*2.5):i).padStart(2,"0")}</span>`).join("");
  const names=state.showcase?["6 SHAPE ACTS","DRUMS · BASS · PAD · LEAD","HAHAHACK CALLOUTS","ACID BUILD → WHITEOUT"]:["ORBIT_01","DRUMS + BASS","BEAT MOD","BLOOM RISE"];$("#clips").innerHTML=tracks.map((t,i)=>`<div class="clip" style="--track-color:${t[1]};left:${state.showcase?i*3+1:i*7+2}%;width:${state.showcase?96-i*4:82-i*8}%">${names[i]}<b></b></div>`).join("");
  $("#trackArea").onpointerdown=e=>{const r=e.currentTarget.getBoundingClientRect();state.time=Math.max(0,Math.min(state.duration,(e.clientX-r.left)/r.width*state.duration));updateTransport();};
}
function updateTransport(){
  const totalFrames=Math.floor(state.time*60), sec=Math.floor(totalFrames/60), frame=totalFrames%60;
  $("#timecode").textContent=`00:${String(sec).padStart(2,"0")}:${String(frame).padStart(2,"0")}`;$("#durationCode").textContent=state.duration>=60?"/ 01:00:00":`/ 00:${String(state.duration).padStart(2,"0")}:00`;$("#playhead").style.left=`${state.time/state.duration*100}%`;
}
function togglePlay(force){
  state.playing=force??!state.playing;
  $("#playBtn").textContent=state.playing?"❚❚":"▶";$("#runBtn .play-symbol").textContent=state.playing?"■":"▶";
  if(audioEngine.ctx){
    if(state.playing&&state.audio.enabled){audioEngine.ctx.resume();resetAudioClock();setAudioGain(state.audio.volume);}
    else setAudioGain(0);
  }
}

async function ensureAudio(){
  if(audioEngine.ctx)return audioEngine.ctx;
  const AudioContext=window.AudioContext||window.webkitAudioContext;if(!AudioContext)return null;
  const ctx=new AudioContext(),master=ctx.createGain(),compressor=ctx.createDynamicsCompressor(),analyser=ctx.createAnalyser();
  compressor.threshold.value=-18;compressor.knee.value=14;compressor.ratio.value=5;compressor.attack.value=.004;compressor.release.value=.2;
  analyser.fftSize=64;analyser.smoothingTimeConstant=.72;master.gain.value=0;master.connect(compressor).connect(analyser).connect(ctx.destination);
  const noise=ctx.createBuffer(1,ctx.sampleRate,ctx.sampleRate);const channel=noise.getChannelData(0);for(let i=0;i<channel.length;i++)channel[i]=Math.random()*2-1;
  Object.assign(audioEngine,{ctx,master,analyser,noise,nextTime:ctx.currentTime+.04,step:0,spectrum:new Uint8Array(analyser.frequencyBinCount)});
  const reportState=()=>{$("#audioToggle").dataset.context=ctx.state;$("#audioToggle").title=ctx.state==="running"?"Web Audio is running":"Click to unlock Web Audio";};ctx.onstatechange=reportState;reportState();
  return ctx;
}
function setAudioGain(value){if(!audioEngine.ctx)return;audioEngine.master.gain.cancelScheduledValues(audioEngine.ctx.currentTime);audioEngine.master.gain.setTargetAtTime(value,audioEngine.ctx.currentTime,.025);}
function resetAudioClock(){if(!audioEngine.ctx)return;const stepDuration=60/state.bpm/4,totalSteps=Math.max(16,Math.round(state.duration/stepDuration));audioEngine.step=Math.floor(state.time/stepDuration)%totalSteps;audioEngine.nextTime=audioEngine.ctx.currentTime+.04;}
function tone(time,freq,duration,gain=.1,type="sine",destination=audioEngine.master){
  const {ctx}=audioEngine,o=ctx.createOscillator(),g=ctx.createGain();o.type=type;o.frequency.setValueAtTime(freq,time);g.gain.setValueAtTime(.0001,time);g.gain.exponentialRampToValueAtTime(gain,time+.008);g.gain.exponentialRampToValueAtTime(.0001,time+duration);o.connect(g).connect(destination);o.start(time);o.stop(time+duration+.02);
}
function kick(time){const runtime=showParameters(),{ctx}=audioEngine,o=ctx.createOscillator(),g=ctx.createGain();o.frequency.setValueAtTime(145,time);o.frequency.exponentialRampToValueAtTime(42,time+.15);g.gain.setValueAtTime(.7,time);g.gain.exponentialRampToValueAtTime(.0001,time+.2+runtime.audioDecay*.18);o.connect(g).connect(audioEngine.master);o.start(time);o.stop(time+.5);}
function noiseHit(time,duration,gain,frequency){const {ctx}=audioEngine,s=ctx.createBufferSource(),f=ctx.createBiquadFilter(),g=ctx.createGain();s.buffer=audioEngine.noise;f.type="bandpass";f.frequency.value=frequency;f.Q.value=.8;g.gain.setValueAtTime(gain,time);g.gain.exponentialRampToValueAtTime(.0001,time+duration);s.connect(f).connect(g).connect(audioEngine.master);s.start(time);s.stop(time+duration+.02);}
function bass(time,step,midi){const runtime=showParameters(),notes=[36,36,43,36,39,36,46,43],note=midi??notes[Math.floor(step/2)%notes.length],freq=440*Math.pow(2,(note-69)/12),ctx=audioEngine.ctx,filter=ctx.createBiquadFilter();filter.type="lowpass";filter.frequency.setValueAtTime(runtime.audioCutoff,time);filter.frequency.exponentialRampToValueAtTime(Math.max(120,runtime.audioCutoff*.35),time+.22);filter.Q.value=4+runtime.audioDrive*10;tone(time,freq,.24+runtime.audioDecay*.3,.13,"sawtooth",filter);filter.connect(audioEngine.master);}
function scheduleStep(step,time){
  const stepDuration=60/state.bpm/4,seconds=step*stepDuration%state.duration,section=Math.min(5,Math.floor(seconds/(state.showcase?5:10))),s=step%16,bar=Math.floor(step/16),kickPatterns=[[0,7,8,11],[0,3,7,8,11,14],[0,6,8,10,14],[0,8,11],[0,3,6,8,10,13,15],[0,2,4,7,8,10,12,14]][section];
  if(kickPatterns.includes(s))kick(time);if(s===4||s===12){noiseHit(time,.14,.18,1500);tone(time,180,.1,.07,"triangle");}if(s%(section>=4?1:2)===0)noiseHit(time,.045,s%4===0?.06:.032,7800);
  const bassPatterns=[[36,36,43,36,39,36,46,43],[36,43,48,43,39,46,51,46],[36,36,39,43,48,43,39,36],[36,36,35,35,34,34,31,31],[36,39,43,46,48,46,43,39],[36,43,48,51,55,51,48,43]][section];if(s%2===0)bass(time,step,bassPatterns[Math.floor(s/2)]);
  const chords=[[48,51,55],[44,48,51],[51,55,58],[46,50,53]];if(s===0)chords[bar%4].forEach((m,i)=>tone(time+i*.015,440*Math.pow(2,(m-69)/12),1.65,.02,section===3?"triangle":"sine"));
  if(section>=1&&s%2===1){const lead=[72,75,79,82,79,75,70,67][(step>>1)%8]+(section===5?12:0);tone(time,440*Math.pow(2,(lead-69)/12),.11,section>=4?.045:.025,section===2?"triangle":"square");}
}
function scheduleAudio(){
  if(!audioEngine.ctx||!state.audio.enabled||!state.playing||audioEngine.ctx.state!=="running")return;
  const stepDuration=60/state.bpm/4,totalSteps=Math.max(16,Math.round(state.duration/stepDuration));while(audioEngine.nextTime<audioEngine.ctx.currentTime+.1){scheduleStep(audioEngine.step,audioEngine.nextTime);audioEngine.nextTime+=stepDuration;audioEngine.step=(audioEngine.step+1)%totalSteps;}
}
function updateAudioMeter(){
  const bars=$$("#audioMeter i");if(!audioEngine.analyser||!state.audio.enabled){bars.forEach(b=>b.style.height="2px");return;}
  audioEngine.analyser.getByteFrequencyData(audioEngine.spectrum);bars.forEach((b,i)=>{const v=audioEngine.spectrum[Math.min(audioEngine.spectrum.length-1,i+1)]/255;b.style.height=`${2+v*23}px`;b.style.opacity=.25+v*.75;});
}
function updateBoundMasterGain(){if(!audioEngine.ctx||!state.audio.enabled||!state.playing)return;const value=boundSpecial("Audio Output","masterVolume",state.audio.volume);audioEngine.master.gain.setTargetAtTime(value,audioEngine.ctx.currentTime,.03);}

function initGL(){
  const canvas=$("#glCanvas"), gl=canvas.getContext("webgl2",{antialias:true});
  if(!gl){
    const ctx=canvas.getContext("2d");
    if(ctx){
      glState={fallback:true,ctx};
      $(".viewport-hud span:last-child").textContent="CANVAS FALLBACK";
      return;
    }
    $("#webglError").hidden=false;
    return;
  }
  const vert=`#version 300 es\nin vec2 p;void main(){gl_Position=vec4(p,0.,1.);}`;
  const frag=`#version 300 es
precision highp float;out vec4 o;uniform vec2 r;uniform float t,yaw,pitch,dist,twist,bloom,vignette,pulse,scale,rough,exposure,shapeMode,actIndex,textureView,texScale,texSpeed,texWarp,texContrast,texKaleido,texMix,multiplyCount,multiplySpread,bpm;uniform vec3 color,accent;
mat2 rot(float a){float c=cos(a),s=sin(a);return mat2(c,-s,s,c);} float sdTorus(vec3 p,vec2 q){vec2 x=vec2(length(p.xz)-q.x,p.y);return length(x)-q.y;}float sdBox(vec3 p,vec3 b){vec3 q=abs(p)-b;return length(max(q,0.))+min(max(q.x,max(q.y,q.z)),0.);}
float map(vec3 p){p.xz*=rot(twist*.22*sin(p.y*1.6+t*.22));float A=actIndex;if(A<.5){float d=sdTorus(p,vec2(1.08*scale,.22));vec3 q=p;q.xy*=rot(1.57);d=min(d,sdTorus(q,vec2(.68*scale,.12)));for(int i=0;i<12;i++){if(float(i)>=multiplyCount)continue;float a=float(i)*6.283/max(1.,multiplyCount)+t*.18;q=p-vec3(cos(a),sin(a*2.)*.35,sin(a))*multiplySpread;q.xy*=rot(a+t*.3);d=min(d,sdTorus(q,vec2(.2,.045)));}return d;}if(A<1.5){p.xy*=rot(t*.26);p.yz*=rot(t*.17);float d=sdBox(p,vec3(.68*scale))-.08;vec3 q=p;for(int i=0;i<3;i++){q=abs(q)*2.05-vec3(1.05);q.xy*=rot(.45+float(i));d=max(d,-sdBox(q,vec3(.16,.5,.16)));d=min(d,length(q)-.12);}return d;}if(A<2.5){float d=length(p)-.48*scale;for(int i=0;i<9;i++){float a=float(i)*.698+t*(.18+float(i)*.008);vec3 q=vec3(cos(a),sin(a*1.7)*.55,sin(a))*multiplySpread;d=min(d,length(p-q)-(.13+.07*sin(t*1.3+float(i))));}vec3 w=p;w.xy*=rot(t*.2);d=min(d,sdTorus(w,vec2(.82,.055)));return d;}if(A<3.5){float sp=max(.45,multiplySpread),h=.45+.65*(.5+.5*sin(dot(floor((p.xz+sp*.5)/sp),vec2(2.1,5.7))+t*.6));vec2 c=mod(p.xz+sp*.5,sp)-sp*.5;float d=sdBox(vec3(c.x,p.y-h*.5,c.y),vec3(.14,h,.14));d=max(d,max(abs(p.x),abs(p.z))-3.1);return d;}if(A<4.5){float seg=max(3.,multiplyCount),a=atan(p.z,p.x),slice=6.283/seg;a=mod(a+slice*.5,slice)-slice*.5;vec3 q=vec3(length(p.xz)-multiplySpread,p.y,a*multiplySpread);float d=length(q)-.12;for(int i=0;i<3;i++){q=abs(q)*1.8-vec3(.36,.28,.18);d=min(d,length(q)-.065);}return d;}float d=length(p)-.34;for(int i=0;i<12;i++){float a=float(i)*.524+t*.32,r=multiplySpread*(.65+.3*sin(float(i)*2.));vec3 q=vec3(cos(a)*r,sin(a*2.3)*.7,sin(a)*r);d=min(d,length(p-q)-(.09+.045*sin(t*2.+float(i))));}vec3 q=p;q.xy*=rot(t*.4);d=min(d,sdTorus(q,vec2(.92,.055)));q.yz*=rot(1.57);d=min(d,sdTorus(q,vec2(.62,.04)));return d;}
float hash(vec2 p){return fract(sin(dot(p,vec2(127.1,311.7)))*43758.5453);}float noise(vec2 p){vec2 i=floor(p),f=fract(p);f=f*f*(3.-2.*f);return mix(mix(hash(i),hash(i+vec2(1,0)),f.x),mix(hash(i+vec2(0,1)),hash(i+1.),f.x),f.y);}
float fbm(vec2 p){float v=0.,a=.5;mat2 m=mat2(.8,.6,-.6,.8);for(int i=0;i<5;i++){v+=a*noise(p);p=m*p*2.03+11.7;a*=.5;}return v;}
vec3 texturePattern(vec2 uv){uv-=.5;float seg=max(2.,floor(texKaleido+.5)),ang=atan(uv.y,uv.x),rad=length(uv),slice=6.283185/seg;ang=abs(mod(ang+t*texSpeed*.08,slice)-slice*.5);uv=vec2(cos(ang),sin(ang))*rad;vec2 flow=vec2(fbm(uv*texScale+vec2(0,t*texSpeed)),fbm(uv*texScale+vec2(5.2,-t*texSpeed*.7)));float n=fbm(uv*texScale+texWarp*(flow-.5)*2.+t*texSpeed*.14),bands=.5+.5*sin(n*(10.+actIndex*3.)+rad*(18.+actIndex*4.)-t*texSpeed*2.),cells=1.-smoothstep(.05,.22,abs(fract(n*5.+rad*actIndex*2.)-.5)),veins=pow(abs(sin((uv.x+uv.y+n)*18.)),8.);if(actIndex<1.5)n=mix(n,cells,.35);else if(actIndex<2.5)n=mix(n,bands,.45);else if(actIndex<3.5)n=mix(n,step(.5,fract(uv.x*6.))*step(.5,fract(uv.y*6.)),.28);else if(actIndex<4.5)n=mix(n,veins,.58);else n=mix(max(bands,cells),veins,.35);n=clamp((n-.5)*texContrast+.5,0.,1.);vec3 pal=mix(color,accent,smoothstep(.1,.9,n));pal=mix(pal,vec3(1.,.65,.3),pow(bands,10.)*.55);return pal*(.28+n*1.28);}
vec3 normal(vec3 p){vec2 e=vec2(.002,0);return normalize(vec3(map(p+e.xyy)-map(p-e.xyy),map(p+e.yxy)-map(p-e.yxy),map(p+e.yyx)-map(p-e.yyx)));}
void main(){vec2 uv=(gl_FragCoord.xy*2.-r)/r.y;if(textureView>.5){vec3 tx=texturePattern(uv*.62);float v=1.-smoothstep(.65,1.35,length(uv));o=vec4(pow(tx*v,vec3(.4545)),1);return;}vec3 ro=vec3(0,0,dist);ro.yz*=rot(-pitch);ro.xz*=rot(yaw);vec3 ta=vec3(0);vec3 ww=normalize(ta-ro),uu=normalize(cross(ww,vec3(0,1,0))),vv=cross(uu,ww),rd=normalize(uv.x*uu+uv.y*vv+1.75*ww);float d=0.,m=0.;vec3 p;for(int i=0;i<112;i++){p=ro+rd*d;m=map(p);if(abs(m)<.001||d>14.)break;d+=m*.62;}vec3 col=vec3(.006,.009,.015);float beat=.5+.5*sin(t*6.283*bpm/60.);if(d<14.){vec3 n=normal(p),l=normalize(vec3(-.5,.8,.4));float dif=max(dot(n,l),0.),rim=pow(1.-max(dot(n,-rd),0.),2.3);float spec=pow(max(dot(reflect(-l,n),-rd),0.),mix(12.,80.,1.-rough));vec3 proc=texturePattern(p.xz*.28+n.xy*.08);vec3 ir=mix(color,proc,texMix);col=ir*(.06+dif*.62)+spec*vec3(1.,.72,.5)*2.4+rim*ir*(1.2+pulse*beat*2.4);}
float gridY=(-1.15-ro.y)/rd.y;if(gridY>0.){vec3 gp=ro+rd*gridY;float g=pow(max(0.,1.-min(abs(fract(gp.x)-.5),abs(fract(gp.z)-.5))*22.),4.)*.08;col+=g*vec3(.15,.3,.35)*exp(-gridY*.08);}float glow=bloom*.014/(abs(m)+.02),rad=length(uv),grain=hash(gl_FragCoord.xy+floor(t*60.));col+=glow*mix(color,vec3(.2,.7,1.),.5);col+=mix(color,accent,.5)*(.025+.035*fbm(uv*3.+t*.03))*(1.-smoothstep(.2,1.5,rad));if(actIndex<.5){float stars=step(.992,hash(floor((uv+vec2(t*.002,0.))*220.)));col+=stars*vec3(.8,.9,1.5)*(1.+beat);}else if(actIndex<1.5){float facets=pow(abs(sin((uv.x-uv.y)*42.+t)),24.);col.r+=facets*.14;col.b+=pow(abs(sin((uv.x+uv.y)*37.-t*.7)),28.)*.22;}else if(actIndex<2.5){float haze=fbm(uv*4.+vec2(t*.06,-t*.03));col+=vec3(.18,.035,.005)*haze*(.5+beat);col=mix(col,col.gbr,.08*beat);}else if(actIndex<3.5){float lum=dot(col,vec3(.299,.587,.114)),scan=.82+.18*sin(gl_FragCoord.y*1.65);col=mix(col,vec3(lum)*vec3(.72,.9,1.15),.72)*scan;col+=step(.985,hash(vec2(floor(uv.y*70.),floor(t*10.))))*.12;}else if(actIndex<4.5){float block=step(.72,hash(vec2(floor(uv.y*24.),floor(t*9.)))),slice=step(.82,hash(vec2(floor(uv.x*18.),floor(t*13.))));col=mix(col,col.bgr,block*.72);col.r+=block*.28;col.g+=slice*.18;col*=.8+.25*sin(gl_FragCoord.y*2.4+t*25.);}else{float ring=exp(-abs(rad-mod(t*.45,1.5))*48.),flash=step(.88,beat);col+=ring*vec3(1.,.25,.08)*(1.4+beat);col=mix(col,vec3(1.),flash*.18);col+=pow(max(0.,1.-rad),8.)*accent*.2;}col*=exposure;col*=1.-vignette*dot(uv,uv);col+=(grain-.5)/180.;o=vec4(pow(max(col,0.),vec3(.4545)),1);}`;
  const compile=(type,src)=>{const s=gl.createShader(type);gl.shaderSource(s,src);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(s));return s};
  try{const prog=gl.createProgram();gl.attachShader(prog,compile(gl.VERTEX_SHADER,vert));gl.attachShader(prog,compile(gl.FRAGMENT_SHADER,frag));gl.linkProgram(prog);const buf=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,buf);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array([-1,-1,3,-1,-1,3]),gl.STATIC_DRAW);gl.useProgram(prog);const loc=gl.getAttribLocation(prog,"p");gl.enableVertexAttribArray(loc);gl.vertexAttribPointer(loc,2,gl.FLOAT,false,0,0);glState={gl,prog,uniform:n=>gl.getUniformLocation(prog,n)};}catch(e){$("#webglError").hidden=false;$("#webglError").textContent=e.message;}
  let drag=null;canvas.onpointerdown=e=>{lastExternalEvent=performance.now()/1000;drag={x:e.clientX,y:e.clientY,yaw:orbit.yaw,pitch:orbit.pitch};canvas.setPointerCapture(e.pointerId)};canvas.onpointermove=e=>{if(drag){orbit.yaw=drag.yaw+(e.clientX-drag.x)*.008;orbit.pitch=Math.max(-1.2,Math.min(1.2,drag.pitch+(e.clientY-drag.y)*.006));}};canvas.onpointerup=()=>drag=null;canvas.onwheel=e=>{e.preventDefault();orbit.distance=Math.max(2.5,Math.min(8,orbit.distance+e.deltaY*.004));};
}
function frame(now){
  const dt=Math.min(.05,(now-lastFrame)/1000);lastFrame=now;if(state.playing){state.time+=dt;if(state.time>=state.duration){if(state.looping)state.time%=state.duration;else{state.time=state.duration;togglePlay(false)}}}updateTransport();
  updateSceneOverlays();updateActUI();updateBindingReadouts();updateBoundMasterGain();scheduleAudio();updateAudioMeter();
  fpsSmooth=fpsSmooth*.94+(1/Math.max(dt,.001))*.06;$("#fps").textContent=`${Math.round(fpsSmooth)} FPS`;$("#renderTime").textContent=`${(dt*1000*.14).toFixed(1)} MS`;
  const audioStatus=!state.audio.enabled?"WEB AUDIO READY":audioEngine.ctx?.state==="running"?"WEB AUDIO LIVE":"WEB AUDIO ARMED";$("#statusMetrics").firstChild.textContent=`${allNodes().length} OPERATORS · ${audioStatus} · `;
  if(glState?.fallback) renderCanvasFallback(glState.ctx);
  else if(glState){const show=showParameters(),motionTime=state.showcase?state.time*2:state.time,{gl,prog,uniform}=glState,c=gl.canvas,dpr=Math.min(devicePixelRatio,2),w=Math.floor(c.clientWidth*dpr),h=Math.floor(c.clientHeight*dpr);if(c.width!==w||c.height!==h){c.width=w;c.height=h;gl.viewport(0,0,w,h);$("#resolution").textContent=`${w} × ${h}`;}gl.useProgram(prog);gl.uniform2f(uniform("r"),w,h);gl.uniform1f(uniform("t"),motionTime);gl.uniform1f(uniform("yaw"),boundSpecial("Camera","cameraYaw",orbit.yaw)+(state.showcase?state.time*.32:0));gl.uniform1f(uniform("pitch"),boundSpecial("Camera","cameraPitch",orbit.pitch)+(state.showcase?Math.sin(state.time*.46)*.16:0));gl.uniform1f(uniform("dist"),state.showcase?show.cameraDistance+Math.sin(state.time*.62)*.22:boundSpecial("Camera","cameraDistance",orbit.distance));for(const [u,k] of [["shapeMode","shapeMode"],["twist","twist"],["bloom","bloom"],["vignette","vignette"],["pulse","pulse"],["scale","scale"],["rough","roughness"],["exposure","exposure"],["texScale","texScale"],["texSpeed","texSpeed"],["texWarp","texWarp"],["texContrast","texContrast"],["texKaleido","texKaleido"],["texMix","texMix"],["multiplyCount","multiplyCount"],["multiplySpread","multiplySpread"]])gl.uniform1f(uniform(u),show[k]);gl.uniform1f(uniform("actIndex"),state.showcase?currentActIndex():show.shapeMode);gl.uniform1f(uniform("bpm"),state.bpm);gl.uniform1f(uniform("textureView"),state.graphMode==="textures"?1:0);const hex=show.color.match(/\w\w/g).map(x=>parseInt(x,16)/255),accent=show.accent.match(/\w\w/g).map(x=>parseInt(x,16)/255);gl.uniform3f(uniform("color"),...hex);gl.uniform3f(uniform("accent"),...accent);gl.drawArrays(gl.TRIANGLES,0,3);}
  requestAnimationFrame(frame);
}

function renderCanvasFallback(ctx){
  const c=ctx.canvas,dpr=Math.min(devicePixelRatio,2),w=Math.floor(c.clientWidth*dpr),h=Math.floor(c.clientHeight*dpr);
  if(c.width!==w||c.height!==h){c.width=w;c.height=h;$("#resolution").textContent=`${w} × ${h}`;}
  ctx.setTransform(1,0,0,1,0,0);const bg=ctx.createRadialGradient(w*.5,h*.48,0,w*.5,h*.48,w*.65);bg.addColorStop(0,"#182126");bg.addColorStop(.35,"#090d10");bg.addColorStop(1,"#030405");ctx.fillStyle=bg;ctx.fillRect(0,0,w,h);
  if(state.graphMode==="textures"){ctx.save();ctx.translate(w/2,h/2);ctx.globalCompositeOperation="lighter";for(let i=0;i<80;i++){const a=i/80*Math.PI*2+state.time*state.params.texSpeed,radius=(40+120*Math.sin(i*12.3+state.time)*.5)*dpr,sz=(4+8*Math.sin(i*7.1+state.time*2)**2)*dpr;ctx.rotate(Math.PI*2/state.params.texKaleido);ctx.fillStyle=i%2?state.params.color:state.params.accent;ctx.globalAlpha=.08+.2*Math.sin(i+state.time)**2;ctx.fillRect(radius,-sz/2,sz*5,sz);}ctx.restore();ctx.globalCompositeOperation="source-over";ctx.globalAlpha=1;return;}
  const beat=.5+.5*Math.sin(state.time*Math.PI*2*(state.bpm/60)), s=Math.min(w,h)*(.23+beat*state.params.pulse*.018)*state.params.scale;
  ctx.save();ctx.translate(w*.5,h*.48);ctx.rotate(orbit.yaw+state.time*.045);ctx.globalCompositeOperation="lighter";
  for(let i=10;i>=0;i--){const a=i/10, hue=10+a*180+state.time*8;ctx.strokeStyle=`hsla(${hue},90%,${48+a*20}%,${.025+a*.055*state.params.bloom})`;ctx.lineWidth=(14+i*2)*dpr;ctx.beginPath();ctx.ellipse(0,0,s*1.35,s*(.34+Math.abs(Math.sin(orbit.pitch))*.2),state.params.twist*.3,0,Math.PI*2);ctx.stroke();}
  ctx.strokeStyle=state.params.color;ctx.globalAlpha=.82;ctx.lineWidth=3*dpr;ctx.beginPath();ctx.ellipse(0,0,s*1.35,s*.34,state.params.twist*.3,0,Math.PI*2);ctx.stroke();ctx.rotate(Math.PI/2.2);ctx.strokeStyle="#25c9cd";ctx.globalAlpha=.55;ctx.beginPath();ctx.ellipse(0,0,s*.88,s*.23,-state.params.twist*.2,0,Math.PI*2);ctx.stroke();ctx.restore();
  ctx.globalCompositeOperation="source-over";ctx.globalAlpha=.22;ctx.strokeStyle="#31505a";ctx.lineWidth=1;const horizon=h*.78;for(let i=-10;i<=10;i++){ctx.beginPath();ctx.moveTo(w*.5+i*w*.05,horizon);ctx.lineTo(w*.5+i*w*.16,h);ctx.stroke();}for(let i=0;i<6;i++){const yy=horizon+(i*i)*h*.009;ctx.beginPath();ctx.moveTo(0,yy);ctx.lineTo(w,yy);ctx.stroke();}ctx.globalAlpha=1;
}
function autosave(){clearTimeout(autosave.t);$("#saveState").textContent="UNSAVED";autosave.t=setTimeout(()=>{localStorage.setItem("werkkzeug-project",JSON.stringify({nodes:state.nodes,connections:state.connections,textureNodes:state.textureNodes,textureConnections:state.textureConnections,postNodes:state.postNodes,postConnections:state.postConnections,audioNodes:state.audioNodes,audioConnections:state.audioConnections,params:state.params,audio:state.audio,bpm:state.bpm,duration:state.duration,showcase:state.showcase,sceneVersion:state.sceneVersion,name:$("#projectName").value}));$("#saveState").textContent="AUTOSAVED";},350);}
async function exportProject(){
  const button=$("[data-action=export]"),label=button.textContent;button.disabled=true;button.textContent="Packing…";$("#saveState").textContent="BUILDING JPEG";
  const data={format:"werkkzeug-web/6",name:$("#projectName").value,bpm:state.bpm,duration:state.duration,showcase:state.showcase,scene:{nodes:state.nodes,connections:state.connections},textures:{engine:"gpu-procedural",nodes:state.textureNodes,connections:state.textureConnections},post:{engine:"webgl-post",nodes:state.postNodes,connections:state.postConnections},audio:{engine:"webaudio-procedural",nodes:state.audioNodes,connections:state.audioConnections,settings:state.audio},parameters:state.params};
  try{const result=await exportExecutableJpeg(data);$("#saveState").textContent=`EXPORTED ${(result.blob.size/1024).toFixed(1)} KB`;$("#saveState").dataset.preview=result.previewUrl;}
  catch(error){console.error(error);$("#saveState").textContent="EXPORT FAILED";alert(`Could not build executable demo: ${error.message}`);}
  finally{button.disabled=false;button.textContent=label;}
}
function newProject(){if(!confirm("Start a new project? Your current work is saved locally."))return;state.nodes=structuredClone(defaultNodes);state.connections=structuredClone(defaultConnections);state.textureNodes=structuredClone(defaultTextureNodes);state.textureConnections=structuredClone(defaultTextureConnections);state.postNodes=structuredClone(defaultPostNodes);state.postConnections=structuredClone(defaultPostConnections);state.audioNodes=structuredClone(defaultAudioNodes);state.audioConnections=structuredClone(defaultAudioConnections);state.graphMode="scene";state.params={...defaults};state.audio={enabled:false,volume:.42};state.time=0;state.duration=30;state.bpm=264;state.showcase=true;state.sceneVersion=DEFAULT_SCENE_VERSION;state.selected="TXT_00";setAudioGain(0);updateAudioUI();$("#projectName").value="HAHAHACK · ABSURD MACHINE";$("#bpm").value=state.bpm;renderGraph();renderInspector();initTimeline();autosave();}

function updateAudioUI(){
  $("#audioToggle").classList.toggle("active",state.audio.enabled);$("#audioToggle b").textContent=state.audio.enabled?"SOUND ON":"SOUND OFF";$("#masterVolume").value=state.audio.volume;
}

function placeDroppedOperator(payload,clientX,clientY){
  const canvas=$("#graphCanvas"),rect=canvas.getBoundingClientRect();if(clientX<rect.left||clientX>rect.right||clientY<rect.top||clientY>rect.bottom)return false;const position={x:Math.max(0,(clientX-rect.left)/state.zoom-63),y:Math.max(0,(clientY-rect.top)/state.zoom-35)};payload.opid?addCompatibilityNode(operatorById.get(payload.opid),position):addNode(payload.kind,position);return true;
}

function bindOperatorCard(button){
  const payload={kind:button.dataset.kind,opid:button.dataset.opid||""};let drag=null,suppressClick=false;
  button.onclick=()=>{if(suppressClick){suppressClick=false;return;}payload.opid?addCompatibilityNode(operatorById.get(payload.opid)):addNode(payload.kind);};
  button.onpointerdown=e=>{if(e.button!==0)return;drag={id:e.pointerId,x:e.clientX,y:e.clientY,active:false,ghost:null};const move=event=>{if(!drag||event.pointerId!==drag.id)return;if(!drag.active&&Math.hypot(event.clientX-drag.x,event.clientY-drag.y)>6){drag.active=true;drag.ghost=document.createElement("div");drag.ghost.className="operator-drag-ghost";drag.ghost.textContent=payload.kind;document.body.append(drag.ghost);}if(drag.active){drag.ghost.style.transform=`translate(${event.clientX+12}px,${event.clientY+12}px)`;const r=$("#graphCanvas").getBoundingClientRect(),inside=event.clientX>=r.left&&event.clientX<=r.right&&event.clientY>=r.top&&event.clientY<=r.bottom;$("#graphCanvas").classList.toggle("drop-ready",inside);}};const up=event=>{if(!drag||event.pointerId!==drag.id)return;if(drag.active){suppressClick=true;placeDroppedOperator(payload,event.clientX,event.clientY);drag.ghost?.remove();$("#graphCanvas").classList.remove("drop-ready");}drag=null;window.removeEventListener("pointermove",move);window.removeEventListener("pointerup",up);window.removeEventListener("pointercancel",up);};window.addEventListener("pointermove",move);window.addEventListener("pointerup",up);window.addEventListener("pointercancel",up);};
}

function setupGraphDrop(){
  const canvas=$("#graphCanvas");
  canvas.ondragenter=e=>{if(e.dataTransfer.types.includes("application/x-werkkzeug-op")){e.preventDefault();canvas.classList.add("drop-ready");}};
  canvas.ondragover=e=>{if(e.dataTransfer.types.includes("application/x-werkkzeug-op")){e.preventDefault();e.dataTransfer.dropEffect="copy";}};
  canvas.ondragleave=e=>{if(!canvas.contains(e.relatedTarget))canvas.classList.remove("drop-ready");};
  canvas.ondrop=e=>{e.preventDefault();canvas.classList.remove("drop-ready");let payload;try{payload=JSON.parse(e.dataTransfer.getData("application/x-werkkzeug-op"));}catch{return;}placeDroppedOperator(payload,e.clientX,e.clientY);};
}

function setupResizablePanels(){
  const root=document.documentElement,defaults={library:216,inspector:250,timeline:166,viewport:null};let layout={...defaults};try{layout={...layout,...JSON.parse(localStorage.getItem("werkkzeug-layout")||"{}")};}catch{}
  const apply=()=>{root.style.setProperty("--library-width",`${layout.library}px`);root.style.setProperty("--inspector-width",`${layout.inspector}px`);root.style.setProperty("--timeline-height",`${layout.timeline}px`);root.style.setProperty("--viewport-height",layout.viewport?`${layout.viewport}px`:"58%");requestAnimationFrame(()=>{constrainGraphNodes();drawWires();});};
  const bind=(selector,move)=>{const handle=$(selector);let active=false,pointerId=-1;const onMove=e=>{if(!active||e.pointerId!==pointerId)return;move(e);apply();};const finish=e=>{if(!active||(e.pointerId!==undefined&&e.pointerId!==pointerId))return;active=false;handle.classList.remove("active");document.body.classList.remove("resizing");window.removeEventListener("pointermove",onMove);window.removeEventListener("pointerup",finish);window.removeEventListener("pointercancel",finish);localStorage.setItem("werkkzeug-layout",JSON.stringify(layout));};handle.onpointerdown=e=>{e.preventDefault();active=true;pointerId=e.pointerId;handle.classList.add("active");document.body.classList.add("resizing");window.addEventListener("pointermove",onMove);window.addEventListener("pointerup",finish);window.addEventListener("pointercancel",finish);};handle.onlostpointercapture=finish;handle.ondblclick=()=>{layout={...defaults};apply();localStorage.removeItem("werkkzeug-layout");};};
  bind("#resizeLibrary",e=>layout.library=Math.max(150,Math.min(400,e.clientX)));
  bind("#resizeInspector",e=>layout.inspector=Math.max(200,Math.min(460,innerWidth-e.clientX)));
  bind("#resizeTimeline",e=>layout.timeline=Math.max(120,Math.min(360,innerHeight-e.clientY-24)));
  bind("#resizeViewport",e=>{const rect=$(".center-stage").getBoundingClientRect();layout.viewport=Math.max(120,Math.min(rect.height-120,e.clientY-rect.top));});
  apply();
}

function projectSnapshot(){return {nodes:state.nodes,connections:state.connections,textureNodes:state.textureNodes,textureConnections:state.textureConnections,postNodes:state.postNodes,postConnections:state.postConnections,audioNodes:state.audioNodes,audioConnections:state.audioConnections,params:state.params,audio:state.audio,bpm:state.bpm,duration:state.duration,showcase:state.showcase,sceneVersion:state.sceneVersion,name:$("#projectName").value};}
function activateWorkspace(mode){const labels={scene:"SCENE",textures:"TEXTURES",post:"POST FX",audio:"AUDIO"};$$("#graphTabs button").forEach(button=>button.classList.toggle("active",button.textContent.trim()===labels[mode]));switchGraphMode(mode);}
function clearTutorialFocus(){$$(".tutorial-focus").forEach(element=>element.classList.remove("tutorial-focus"));}
function renderTutorialGallery(){$("#tutorialGrid").innerHTML=TUTORIALS.map(tutorial=>`<button class="tutorial-card" data-tutorial="${tutorial.id}" style="--tutorial-accent:${tutorial.accent}"><small>${tutorial.level}</small><b>${tutorial.duration}</b><strong>${tutorial.title}</strong><p>${tutorial.description}</p><span>LOAD TUTORIAL →</span></button>`).join("");$$("[data-tutorial]").forEach(button=>button.onclick=()=>loadTutorial(button.dataset.tutorial));}
function renderDemoGallery(){$("#demoGrid").innerHTML=BUILTIN_DEMOS.map(demo=>`<button class="demo-card" data-demo="${demo.id}" style="--demo-a:${demo.colors[0]};--demo-b:${demo.colors[1]}"><div class="demo-thumb"></div><div class="demo-card-content"><small>${demo.tag} · ${demo.bpm} BPM</small><strong>${demo.title}</strong><p>${demo.description}</p><span>LOAD & REMIX →</span></div></button>`).join("");$$("[data-demo]").forEach(button=>button.onclick=()=>loadBuiltInDemo(button.dataset.demo));}
function loadBuiltInDemo(id){
  const demo=BUILTIN_DEMOS.find(item=>item.id===id);if(!demo)return;localStorage.setItem("werkkzeug-project-before-demo",JSON.stringify(projectSnapshot()));exitTutorial();setAudioGain(0);state.nodes=structuredClone(defaultNodes.filter(node=>!["TXT_00","TXT_BRAND"].includes(node.id)));state.connections=structuredClone(defaultConnections.filter(connection=>!["TXT_00","TXT_BRAND"].some(id=>connection.includes(id))));state.textureNodes=structuredClone(defaultTextureNodes);state.textureConnections=structuredClone(defaultTextureConnections);state.postNodes=structuredClone(defaultPostNodes);state.postConnections=structuredClone(defaultPostConnections);state.audioNodes=structuredClone(defaultAudioNodes);state.audioConnections=structuredClone(defaultAudioConnections);state.params={...defaults,...demo.params};state.audio={enabled:false,volume:.42};state.bpm=demo.bpm;state.duration=12;state.showcase=false;state.time=0;$("#projectName").value=`DEMO · ${demo.title.toUpperCase()}`;$("#bpm").value=state.bpm;$("#demoModal").hidden=true;updateAudioUI();initTimeline();activateWorkspace("scene");selectNode("MAT_04");togglePlay(true);autosave();
}
function loadTutorial(id){
  const tutorial=TUTORIALS.find(item=>item.id===id);if(!tutorial)return;localStorage.setItem("werkkzeug-project-before-tutorial",JSON.stringify(projectSnapshot()));setAudioGain(0);state.nodes=structuredClone(defaultNodes.filter(node=>!["TXT_00","TXT_BRAND"].includes(node.id)));state.connections=structuredClone(defaultConnections.filter(connection=>!["TXT_00","TXT_BRAND"].some(id=>connection.includes(id))));state.textureNodes=structuredClone(defaultTextureNodes);state.textureConnections=structuredClone(defaultTextureConnections);state.postNodes=structuredClone(defaultPostNodes);state.postConnections=structuredClone(defaultPostConnections);state.audioNodes=structuredClone(defaultAudioNodes);state.audioConnections=structuredClone(defaultAudioConnections);state.params={...defaults,...tutorial.project.params};state.audio={enabled:false,volume:.42};state.bpm=tutorial.project.bpm;state.duration=12;state.showcase=false;state.time=0;$("#projectName").value=tutorial.project.name;$("#bpm").value=state.bpm;activeTutorial=tutorial;tutorialStep=0;$("#tutorialModal").hidden=true;$("#tutorialGuide").hidden=false;updateAudioUI();initTimeline();activateWorkspace(tutorial.project.mode);showTutorialStep();autosave();
}
function showTutorialStep(){
  if(!activeTutorial)return;clearTutorialFocus();const step=activeTutorial.steps[tutorialStep];if(step.mode)activateWorkspace(step.mode);if(step.node&&allNodes().some(node=>node.id===step.node))selectNode(step.node);$("#tutorialProgress").textContent=`${activeTutorial.title.toUpperCase()} · STEP ${tutorialStep+1} / ${activeTutorial.steps.length}`;$("#tutorialStepTitle").textContent=step.title;$("#tutorialStepBody").textContent=step.body;$("#tutorialPrev").disabled=tutorialStep===0;$("#tutorialNext").textContent=tutorialStep===activeTutorial.steps.length-1?"FINISH ✓":"NEXT →";requestAnimationFrame(()=>{const target=$(step.target);if(target)target.classList.add("tutorial-focus");});
}
function exitTutorial(){clearTutorialFocus();$("#tutorialGuide").hidden=true;activeTutorial=null;tutorialStep=0;}
function navigateTutorial(direction){const now=performance.now();if(!activeTutorial||now-tutorialNavTime<300)return;tutorialNavTime=now;if(direction<0&&tutorialStep>0){tutorialStep--;showTutorialStep();}else if(direction>0&&tutorialStep>=activeTutorial.steps.length-1)exitTutorial();else if(direction>0){tutorialStep++;showTutorialStep();}}

function bindUI(){
  renderLibrary();renderGraph();renderInspector();initTimeline();
  setupGraphDrop();setupResizablePanels();renderTutorialGallery();renderDemoGallery();
  window.addEventListener("werkkzeug-trigger",()=>lastExternalEvent=performance.now()/1000);globalThis.werkkzeugTrigger=()=>window.dispatchEvent(new Event("werkkzeug-trigger"));
  $("#nodeSearch").oninput=e=>renderLibrary(e.target.value);$("#projectName").oninput=autosave;
  $("#audioToggle").onclick=async()=>{const ctx=await ensureAudio();if(!ctx)return;state.audio.enabled=!state.audio.enabled;updateAudioUI();autosave();if(state.audio.enabled){ctx.resume().then(()=>{resetAudioClock();setAudioGain(state.playing?state.audio.volume:0);$("#audioToggle").dataset.context=ctx.state;});}else setAudioGain(0);};
  $("#masterVolume").oninput=e=>{state.audio.volume=Number(e.target.value);if(state.audio.enabled&&state.playing)setAudioGain(state.audio.volume);autosave();};
  $("[data-action=new]").onclick=newProject;$("[data-action=save]").onclick=autosave;$("[data-action=export]").onclick=exportProject;
  $("#playBtn").onclick=()=>togglePlay();$("#runBtn").onclick=()=>togglePlay();$("#toStart").onclick=()=>{state.time=0;updateTransport()};$("#prevFrame").onclick=()=>{state.time=Math.max(0,state.time-1/60)};$("#nextFrame").onclick=()=>{state.time=Math.min(state.duration,state.time+1/60)};
  $("#loopBtn").onclick=e=>{state.looping=!state.looping;e.currentTarget.classList.toggle("active",state.looping)};$("#bpm").onchange=e=>{state.bpm=Number(e.target.value);resetAudioClock();autosave();};
  $("#enableNode").onclick=()=>{const n=allNodes().find(x=>x.id===state.selected);if(!n)return;n.enabled=!n.enabled;renderGraph();renderInspector();updateSceneOverlays();autosave()};$("#deleteNode").onclick=removeSelected;
  $("#addNodeBtn").onclick=e=>{const m=$("#addMenu");m.hidden=!m.hidden;m.style.top="7px";m.style.right="7px";m.innerHTML=operatorCatalog.flatMap(g=>g.items).map(i=>`<button data-kind="${i[0]}" ${i[4]?`data-opid="${i[4]}"`:""}><span class="op-icon ${i[2]}">${i[1]}</span>${i[0]}${i[3]?`<small>${i[3]}</small>`:""}</button>`).join("");$$('button',m).forEach(b=>b.onclick=()=>b.dataset.opid?addCompatibilityNode(operatorById.get(b.dataset.opid)):addNode(b.dataset.kind));};
  $("#zoomIn").onclick=()=>setZoom(state.zoom+.1);$("#zoomOut").onclick=()=>setZoom(state.zoom-.1);$("#frameBtn").onclick=()=>setZoom(1);$("#fullscreenBtn").onclick=()=>$(".viewport").requestFullscreen?.();
  $("#gridBtn").onclick=e=>{e.currentTarget.classList.toggle("active");$("#graphCanvas").style.backgroundImage=e.currentTarget.classList.contains("active")?"":"none"};
  $$("#viewMode button").forEach(b=>b.onclick=()=>{$$("#viewMode button").forEach(x=>x.classList.remove("active"));b.classList.add("active");if(b.dataset.view==="camera")orbit={yaw:.15,pitch:.1,distance:4.5};});
  $$("#graphTabs button").forEach(b=>b.onclick=()=>{$$("#graphTabs button").forEach(x=>x.classList.remove("active"));b.classList.add("active");const label=b.textContent.trim();switchGraphMode(label==="TEXTURES"?"textures":label==="POST FX"?"post":label==="AUDIO"?"audio":"scene")});
  $("#aboutBtn").onclick=()=>$("#aboutModal").hidden=false;$("#compatBtn").onclick=()=>{const counts=new Map();WZ4_OPERATORS.forEach(op=>counts.set(op.family,(counts.get(op.family)||0)+1));$("#compatFamilies").innerHTML=[...counts].map(([family,count])=>`<div class="compat-family"><span>${family}</span><b>${count}</b></div>`).join("");$("#compatModal").hidden=false;};$$('.modal-close').forEach(b=>b.onclick=()=>b.closest('.modal').hidden=true);$$('.modal').forEach(m=>m.onclick=e=>{if(e.target===m)m.hidden=true});
  $("#tutorialsBtn").onclick=()=>$("#tutorialModal").hidden=false;$("#tutorialExit").onclick=exitTutorial;$("#tutorialPrev").onclick=()=>navigateTutorial(-1);$("#tutorialNext").onclick=()=>navigateTutorial(1);
  $("#demosBtn").onclick=()=>$("#demoModal").hidden=false;
  $("#actSelector").onchange=e=>selectAct(e.target.value);$("#prevAct").onclick=()=>selectAct(currentActIndex()-1);$("#nextAct").onclick=()=>selectAct(currentActIndex()+1);
  window.onresize=drawWires;document.onkeydown=e=>{lastExternalEvent=performance.now()/1000;if(e.target.matches("input,select,textarea"))return;if(e.code==="Space"){e.preventDefault();togglePlay()}if(e.key.toLowerCase()==="m")$("#audioToggle").click();if(e.key==="Delete"||e.key==="Backspace"){e.preventDefault();removeSelected();}if(e.key==="[")selectAct(currentActIndex()-1);if(e.key==="]")selectAct(currentActIndex()+1);if(e.key.toLowerCase()==="f")setZoom(1);if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==="s"){e.preventDefault();autosave()}};
  updateAudioUI();
}
function setZoom(z){state.zoom=Math.max(.6,Math.min(1.4,z));$("#nodes").style.transform=`scale(${state.zoom})`;$("#nodes").style.transformOrigin="0 0";$("#zoomLabel").textContent=Math.round(state.zoom*100)+"%";drawWires();}

window.scrollTo(0,0);
const saved=localStorage.getItem("werkkzeug-project");if(saved){try{const s=JSON.parse(saved);if(s.sceneVersion===DEFAULT_SCENE_VERSION){const legacyNodes=(s.nodes||state.nodes).filter(n=>!n.type?.includes("POST FX")&&!n.type?.includes("AUDIO OPERATOR"));Object.assign(state,{nodes:legacyNodes,connections:s.connections||state.connections,textureNodes:s.textureNodes||state.textureNodes,textureConnections:s.textureConnections||state.textureConnections,postNodes:s.postNodes||state.postNodes,postConnections:s.postConnections||state.postConnections,audioNodes:s.audioNodes||state.audioNodes,audioConnections:s.audioConnections||state.audioConnections,params:{...state.params,...s.params},audio:{...state.audio,...s.audio},bpm:s.bpm||state.bpm,duration:s.duration||state.duration,showcase:s.showcase??state.showcase,sceneVersion:s.sceneVersion});state.audio.enabled=false;if(s.name)$("#projectName").value=s.name;}else localStorage.setItem(`werkkzeug-project-before-scene-${DEFAULT_SCENE_VERSION}`,saved);$("#bpm").value=state.bpm;}catch{}}
bindUI();initGL();togglePlay(true);requestAnimationFrame(frame);
