import { WZ4_OPERATORS } from "./operator-manifest.js";
import { COMPAT_COLORS, compatModeFor, compatRuntimeFor } from "./compat-runtime.js";

const GUIDED_TUTORIALS = [
  {
    id:"torus-basics",title:"Torus Fundamentals",level:"BEGINNER",duration:"4 MIN",accent:"#5da7ff",
    description:"Build a procedural hero object, tune its material, and orbit the live camera.",
    project:{name:"TUTORIAL · TORUS STUDY",bpm:128,mode:"scene",params:{color:"#ff583e",accent:"#20bed0",scale:1,twist:.35,metallic:.88,roughness:.2,bloom:.42,pulse:.18,exposure:1.12}},
    steps:[
      {title:"The scene graph",body:"Every box is a live operator. Data flows left to right into Main Output.",mode:"scene",node:"GEO_02",target:"#graphCanvas"},
      {title:"Shape the primitive",body:"Torus Field is the geometry source. Use Scale and Detail in the inspector to change its silhouette.",mode:"scene",node:"GEO_02",target:"#inspectorContent"},
      {title:"Add deformation",body:"Select Infinite Twist and adjust Amount. The viewport responds every frame.",mode:"scene",node:"MOD_03",target:'.node[data-id="MOD_03"]'},
      {title:"Navigate the viewport",body:"Drag in the viewport to orbit and use the wheel to zoom. Your project is autosaved.",mode:"scene",target:"#glCanvas"}
    ]
  },
  {
    id:"liquid-texture",title:"Animated Liquid Texture",level:"INTERMEDIATE",duration:"6 MIN",accent:"#25c9cd",
    description:"Create flowing GPU noise, fold it radially, and map it onto the scene material.",
    project:{name:"TUTORIAL · LIQUID SIGNAL",bpm:122,mode:"textures",params:{color:"#ff426d",accent:"#25d9d3",texScale:5.4,texSpeed:.48,texWarp:1.85,texContrast:1.72,texKaleido:7,texMix:.86,bloom:.68,vignette:.12,exposure:1.08}},
    steps:[
      {title:"Texture workspace",body:"This independent graph generates a texture entirely on the GPU.",mode:"textures",node:"TEX_01",target:"#graphCanvas"},
      {title:"Animate the noise",body:"Frequency controls detail; Speed advances the field using global demo time.",mode:"textures",node:"TEX_01",target:"#inspectorContent"},
      {title:"Warp the domain",body:"Liquid Warp feeds noise back into its own coordinates, producing fluid motion.",mode:"textures",node:"TEX_02",target:'.node[data-id="TEX_02"]'},
      {title:"Map it to material",body:"Material Map sends the final animated texture into the Scene material. Return to Scene to see it on the torus.",mode:"textures",node:"TEX_05",target:'.node[data-id="TEX_05"]'}
    ]
  },
  {
    id:"cinematic-post",title:"Cinematic Post Stack",level:"INTERMEDIATE",duration:"5 MIN",accent:"#9b7bff",
    description:"Balance bloom, grading, exposure and vignette in a dedicated post-processing graph.",
    project:{name:"TUTORIAL · AFTERIMAGE",bpm:136,mode:"post",params:{color:"#ff7a3d",accent:"#6c4dff",bloom:1.05,vignette:.38,exposure:.82,texContrast:1.8,roughness:.32,pulse:.28}},
    steps:[
      {title:"Post-processing chain",body:"Scene Color enters on the left. Each operator modifies the rendered frame before Final Image.",mode:"post",node:"POST_01",target:"#graphCanvas"},
      {title:"Bloom highlights",body:"Hot Bloom spreads energy from bright pixels. Keep it intentional to preserve contrast.",mode:"post",node:"POST_02",target:"#inspectorContent"},
      {title:"Filmic grade",body:"Color Grade balances exposure and contrast after lighting and material evaluation.",mode:"post",node:"POST_03",target:'.node[data-id="POST_03"]'},
      {title:"Frame with vignette",body:"Vignette darkens the perimeter and guides attention toward the procedural form.",mode:"post",node:"POST_04",target:"#inspectorContent"}
    ]
  },
  {
    id:"beat-audio",title:"Beat-Synced Audio",level:"ADVANCED",duration:"7 MIN",accent:"#55d887",
    description:"Sequence procedural drums and bass, then use the same beat signal to drive the visuals.",
    project:{name:"TUTORIAL · PULSE ENGINE",bpm:110,mode:"audio",params:{color:"#ff365f",accent:"#36ffd1",pulse:.86,twist:1.9,bloom:.82,audioCutoff:680,audioDecay:.42,audioDrive:.72,exposure:1.2}},
    steps:[
      {title:"Audio graph",body:"Beat Clock drives both the Drum Machine and Demo Bass at the project BPM.",mode:"audio",node:"AUDIO_01",target:"#graphCanvas"},
      {title:"Shape the rhythm",body:"Drum decay and drive change the procedural transient synthesis in real time.",mode:"audio",node:"AUDIO_02",target:"#inspectorContent"},
      {title:"Sculpt the bass",body:"The bass low-pass cutoff and resonance are exposed as live operator parameters.",mode:"audio",node:"AUDIO_03",target:"#inspectorContent"},
      {title:"Unlock Web Audio",body:"Click SOUND OFF once. Browsers require this gesture before audio can play.",mode:"audio",target:"#audioToggle"},
      {title:"Shared beat signal",body:"Return to Scene and inspect Beat Pulse. Audio and visuals now share the same clock.",mode:"scene",node:"SIG_01",target:'.node[data-id="SIG_01"]'}
    ]
  },
  {
    id:"texture-real-concrete",title:"Texture 06 · Weathered Concrete Composition",level:"REALISTIC COMPOSITION",duration:"7 MIN",accent:"#aeb8bd",description:"Compose concrete from structural seams, broad tonal breakup, fine aggregate, and vertical weathering instead of one noisy color field.",
    project:{name:"MATERIAL STUDY · WEATHERED CONCRETE",bpm:92,mode:"textures",visualMode:"cityMaterials",params:{color:"#31383d",accent:"#bac4c7",texScale:6.2,texSpeed:0,texWarp:1.3,texContrast:1.8,texKaleido:4,texMix:.18,bloom:.08,roughness:.78}},focus:{mode:"textures",node:"TEX_02"},
    recipe:{nodeIds:["TEX_01","TEX_02","TEX_03","TEX_05"],connections:[["TEX_01","TEX_02"],["TEX_02","TEX_03"],["TEX_03","TEX_05"]],names:{TEX_01:["Concrete Aggregate","MACRO + MICRO"],TEX_02:["Rain Weathering","VERTICAL MASK"],TEX_03:["Panel Seams","STRUCTURE"],TEX_05:["Concrete Surface","MATERIAL BOARD"]}},
    steps:[{title:"Compose by scale",body:"Real concrete has at least three readable scales: large casting variation, medium stains, and fine aggregate. Establish those scales before adding color.",mode:"textures",node:"TEX_01",target:"#inspectorContent"},{title:"Weather with a directional mask",body:"Use low-frequency distortion for vertical rain streaks and darker collection zones. Weathering should follow gravity, not swirl equally in every direction.",mode:"textures",node:"TEX_02",target:"#inspectorContent"},{title:"Add construction logic",body:"Panel seams are structural information. Keep their rhythm straighter and sharper than the organic noise beneath them.",mode:"textures",node:"TEX_03",target:"#inspectorContent"},{title:"Keep the palette narrow",body:"Concrete realism comes from value and roughness variation. Avoid saturated color; let lighting reveal the aggregate and recessed seams.",mode:"textures",node:"TEX_05",target:"#glCanvas"},{title:"Verify on a camera",body:"Switch to Scene to inspect the same lesson with its dedicated camera. Return here to judge the full material board without a vignette.",mode:"scene",node:"CAM_06",target:"#glCanvas"}]
  },
  {
    id:"texture-real-facade",title:"Texture 07 · Glass Façade Composition",level:"REALISTIC COMPOSITION",duration:"7 MIN",accent:"#75b7c8",description:"Build a believable façade by separating concrete, frames, recessed glass, occupancy, and emission into distinct visual responsibilities.",
    project:{name:"MATERIAL STUDY · GLASS FACADE",bpm:104,mode:"textures",visualMode:"cityMaterials",params:{color:"#20272d",accent:"#7ac6d8",texScale:6.8,texSpeed:0,texWarp:.55,texContrast:2.15,texKaleido:6,texMix:.62,bloom:.12,roughness:.34}},focus:{mode:"textures",node:"TEX_03"},
    recipe:{nodeIds:["TEX_01","TEX_03","TEX_04","TEX_05"],connections:[["TEX_01","TEX_03"],["TEX_03","TEX_04"],["TEX_04","TEX_05"]],names:{TEX_01:["Occupancy Seed","DETERMINISTIC"],TEX_03:["Window Grid","BAYS + FLOORS"],TEX_04:["Glass / Concrete Grade","MATERIAL SPLIT"],TEX_05:["Facade Composite","MATERIAL BOARD"]}},
    steps:[{title:"Start with architectural rhythm",body:"Choose a repeat that reads as floors and bays. Window proportions and spacing must feel plausible before surface noise is introduced.",mode:"textures",node:"TEX_03",target:"#inspectorContent"},{title:"Separate material families",body:"Concrete, metal frames, and glass need distinct value ranges. Dark recessed glass makes the frame thickness legible without painted outlines.",mode:"textures",node:"TEX_04",target:"#inspectorContent"},{title:"Seed occupancy, not brightness",body:"Use noise only to decide which windows are occupied. Keep the window geometry fixed so the building does not boil or deform over time.",mode:"textures",node:"TEX_01",target:"#inspectorContent"},{title:"Use sparse emission",body:"Raise Material Mix to light more rooms. Sparse warm and cool windows feel inhabited; a uniformly glowing grid looks synthetic.",mode:"textures",node:"TEX_05",target:"#glCanvas"},{title:"Check at scene distance",body:"Switch to Scene and verify that window bays survive perspective while fine aggregate disappears naturally with distance.",mode:"scene",node:"CAM_06",target:"#glCanvas"}]
  },
  {
    id:"texture-real-asphalt",title:"Texture 08 · Patched Asphalt Composition",level:"REALISTIC COMPOSITION",duration:"7 MIN",accent:"#9f927c",description:"Layer road aggregate, repair patches, hairline cracks, grime, and restrained lane paint while preserving a dark rough base.",
    project:{name:"MATERIAL STUDY · PATCHED ASPHALT",bpm:96,mode:"textures",visualMode:"cityMaterials",params:{color:"#111416",accent:"#a89a7c",texScale:9.4,texSpeed:0,texWarp:1.45,texContrast:1.95,texKaleido:2,texMix:.12,bloom:.04,roughness:.86}},focus:{mode:"textures",node:"TEX_01"},
    recipe:{nodeIds:["TEX_01","TEX_02","TEX_04","TEX_05"],connections:[["TEX_01","TEX_02"],["TEX_02","TEX_04"],["TEX_04","TEX_05"]],names:{TEX_01:["Stone Aggregate","FINE GRAINS"],TEX_02:["Repairs + Cracks","IRREGULAR MASKS"],TEX_04:["Road Value Grade","NARROW RANGE"],TEX_05:["Asphalt Composite","MATERIAL BOARD"]}},
    steps:[{title:"Anchor a dark base",body:"Asphalt is a narrow, low-value material. Begin dark enough that aggregate appears through lighting rather than as white painted speckles.",mode:"textures",node:"TEX_04",target:"#inspectorContent"},{title:"Add fine aggregate",body:"Raise Grain Scale until individual stones become texture rather than blobs. Roughness controls how frequently brighter aggregate catches the eye.",mode:"textures",node:"TEX_01",target:"#inspectorContent"},{title:"Make repairs larger than grains",body:"Repair patches and stains belong to a much larger scale than aggregate. Domain Warp breaks their edges without turning the road into liquid marble.",mode:"textures",node:"TEX_02",target:"#inspectorContent"},{title:"Reserve clean shapes for markings",body:"Lane paint is manufactured, so it should stay straighter and cleaner than the road. Contrast between procedural wear and graphic markings sells the composition.",mode:"textures",node:"TEX_05",target:"#glCanvas"},{title:"Keep the surface static",body:"Texture Speed is zero. Animate reflected light or rain in a later layer, not the stones, cracks, or repair patches themselves.",mode:"textures",node:"TEX_01",target:"#inspectorContent"}]
  },
  {
    id:"texture-real-city-stack",title:"Texture 09 · Complete City Material Stack",level:"REALISTIC COMPOSITION",duration:"9 MIN",accent:"#f0a76b",description:"Combine structure, surface breakup, weathering, material masks, occupancy, and restrained color into a production-ready procedural city stack.",
    project:{name:"MATERIAL STUDY · COMPLETE CITY STACK",bpm:110,mode:"textures",visualMode:"cityMaterials",params:{color:"#293238",accent:"#e2a36f",texScale:7.2,texSpeed:0,texWarp:1.65,texContrast:2.1,texKaleido:6,texMix:.48,bloom:.1,roughness:.68}},focus:{mode:"textures",node:"TEX_05"},
    recipe:{nodeIds:["TEX_01","TEX_02","TEX_03","TEX_04","TEX_05"],connections:[["TEX_01","TEX_02"],["TEX_02","TEX_03"],["TEX_03","TEX_04"],["TEX_04","TEX_05"]],names:{TEX_01:["Surface Frequencies","MACRO / MICRO"],TEX_02:["Weathering","DIRECTIONAL"],TEX_03:["Structure Masks","PANELS / WINDOWS"],TEX_04:["Material Palette","CONCRETE / GLASS"],TEX_05:["City Material Stack","FINAL COMPOSITE"]}},
    steps:[{title:"1. Establish structure",body:"Think in masks first: wall, seam, frame, glass, road, and marking. These categories describe what the surface is before they describe its color.",mode:"textures",node:"TEX_03",target:"#graphCanvas"},{title:"2. Layer frequencies",body:"Use broad noise for casting and repairs, medium noise for grime, and fine noise for aggregate. Avoid asking one octave to represent every physical scale.",mode:"textures",node:"TEX_01",target:"#inspectorContent"},{title:"3. Apply directional history",body:"Weathering follows gravity, runoff, traffic, and contact edges. Warp those masks gently while keeping architectural structure intact.",mode:"textures",node:"TEX_02",target:"#inspectorContent"},{title:"4. Grade by material",body:"Assign separate ranges to concrete, glass, metal, asphalt, and emission. Realism improves when each family keeps a consistent value and roughness identity.",mode:"textures",node:"TEX_04",target:"#inspectorContent"},{title:"5. Add story sparingly",body:"Occupancy and warm/cool windows suggest life. They are the accent layer, not the base texture, so keep most windows dark.",mode:"textures",node:"TEX_05",target:"#glCanvas"},{title:"6. Validate both views",body:"Inspect the full rectangular board for tiling and balance, then switch to Scene to test scale, perspective, and camera distance.",mode:"scene",node:"CAM_06",target:"#glCanvas"}]
  }
];

const TEXTURE_WORKSHOPS=[
  {
    id:"texture-noise-foundations",title:"Texture 01 · Noise Foundations",level:"TEXTURE WORKSHOP",duration:"4 MIN",accent:"#25c9cd",description:"Build a readable material from layered noise, contrast, and a restrained two-color palette.",
    project:{name:"WORKSHOP · NOISE FOUNDATIONS",bpm:112,mode:"textures",params:{color:"#17232b",accent:"#76d9d2",texScale:4.2,texSpeed:.08,texWarp:.25,texContrast:1.65,texKaleido:2,texMix:.82,bloom:.28,roughness:.48}},focus:{mode:"textures",node:"TEX_01"},
    recipe:{nodeIds:["TEX_01","TEX_04","TEX_05"],connections:[["TEX_01","TEX_04"],["TEX_04","TEX_05"]],names:{TEX_01:["Layered Noise","4 OCTAVES"],TEX_04:["Mineral Palette","DARK / CYAN"],TEX_05:["Material Preview","FULL UV"]}},
    steps:[{title:"Begin with frequency",body:"Start with Animated Noise. Frequency sets the material scale; keep Speed nearly still for a surface rather than an effect.",mode:"textures",node:"TEX_01",target:"#inspectorContent"},{title:"Shape the value range",body:"Contrast separates large forms from fine grain. Raise it until the texture reads clearly, but preserve mid-tones for shading.",mode:"textures",node:"TEX_01",target:"#inspectorContent"},{title:"Color near the end",body:"Palette Map converts one reusable grayscale history into the project Base and Accent colors.",mode:"textures",node:"TEX_04",target:'.node[data-id="TEX_04"]'},{title:"Judge the full UV",body:"Texture Output shows the edge-to-edge result. Look for scale, repetition, and tonal balance before mapping it to geometry.",mode:"textures",node:"TEX_05",target:"#glCanvas"}]
  },
  {
    id:"texture-liquid-warp",title:"Texture 02 · Liquid Warp",level:"TEXTURE WORKSHOP",duration:"5 MIN",accent:"#5da7ff",description:"Distort one noise field with another to create fluid curls without losing the underlying structure.",
    project:{name:"WORKSHOP · LIQUID WARP",bpm:124,mode:"textures",params:{color:"#25104a",accent:"#36f4df",texScale:5.6,texSpeed:.42,texWarp:1.8,texContrast:1.8,texKaleido:3,texMix:.9,bloom:.48}},focus:{mode:"textures",node:"TEX_02"},
    recipe:{nodeIds:["TEX_01","TEX_02","TEX_04","TEX_05"],connections:[["TEX_01","TEX_02"],["TEX_02","TEX_04"],["TEX_04","TEX_05"]],names:{TEX_01:["Flow Source","5 OCTAVES"],TEX_02:["Coordinate Warp","FLUID"],TEX_04:["Deepwater Palette","VIOLET / CYAN"],TEX_05:["Liquid Output","FULL UV"]}},
    steps:[{title:"Create a stable source",body:"Tune the source noise first. A warp cannot rescue a field whose scale is already unreadable.",mode:"textures",node:"TEX_01",target:"#inspectorContent"},{title:"Warp coordinates",body:"Domain Warp bends the sampling coordinates. Increase Amount gradually; extreme values erase useful structure.",mode:"textures",node:"TEX_02",target:"#inspectorContent"},{title:"Animate flow",body:"Speed should be slower than the beat. Bind Amount lightly to Envelope if you want impact ripples.",mode:"textures",node:"TEX_02",target:"#inspectorContent"},{title:"Color and publish",body:"Map the warped grayscale field into a compact palette, then inspect it edge-to-edge at Texture Output.",mode:"textures",node:"TEX_05",target:"#glCanvas"}]
  },
  {
    id:"texture-architectural-panels",title:"Texture 03 · Architectural Panels",level:"TEXTURE WORKSHOP",duration:"5 MIN",accent:"#9b7bff",description:"Turn folded procedural values into façade panels, seams, and controlled material variation.",
    project:{name:"WORKSHOP · ARCHITECTURAL PANELS",bpm:108,mode:"textures",params:{color:"#22262d",accent:"#c7d7dd",texScale:7.2,texSpeed:.04,texWarp:.42,texContrast:2.35,texKaleido:4,texMix:.7,bloom:.18,roughness:.36}},focus:{mode:"textures",node:"TEX_03"},
    recipe:{nodeIds:["TEX_01","TEX_03","TEX_04","TEX_05"],connections:[["TEX_01","TEX_03"],["TEX_03","TEX_04"],["TEX_04","TEX_05"]],names:{TEX_01:["Concrete Grain","FINE"],TEX_03:["Panel Fold","4-WAY"],TEX_04:["Steel Grade","CHARCOAL"],TEX_05:["Facade Panels","FULL UV"]}},
    steps:[{title:"Separate scale layers",body:"Use fine noise for surface grain; the fold operator supplies the large panel organization.",mode:"textures",node:"TEX_01",target:"#inspectorContent"},{title:"Build panel rhythm",body:"Kaleidoscope segments create repeatable bays. Low segment counts read as architecture instead of ornament.",mode:"textures",node:"TEX_03",target:"#inspectorContent"},{title:"Protect the seams",body:"Use contrast to sharpen panel boundaries while retaining noise inside each panel.",mode:"textures",node:"TEX_04",target:"#inspectorContent"},{title:"Check tiling",body:"Inspect the whole rectangle for obvious radial bias or darkened corners before using it on the city.",mode:"textures",node:"TEX_05",target:"#glCanvas"}]
  },
  {
    id:"texture-neon-windows",title:"Texture 04 · Neon Window Mask",level:"TEXTURE WORKSHOP",duration:"5 MIN",accent:"#ff2f8e",description:"Construct a high-contrast mask for window bays, then use it to gate emissive color and beat response.",
    project:{name:"WORKSHOP · NEON WINDOW MASK",bpm:128,mode:"textures",params:{color:"#090d18",accent:"#ff3ba7",texScale:8.4,texSpeed:.12,texWarp:.65,texContrast:2.75,texKaleido:8,texMix:.94,bloom:.72,pulse:.68}},focus:{mode:"textures",node:"TEX_03"},
    recipe:{nodeIds:["TEX_01","TEX_03","TEX_04","TEX_05"],connections:[["TEX_01","TEX_03"],["TEX_03","TEX_04"],["TEX_04","TEX_05"]],names:{TEX_01:["Occupancy Noise","SEEDED"],TEX_03:["Window Mask","8 BAYS"],TEX_04:["Emission Palette","BLACK / PINK"],TEX_05:["Window Output","MASK"]}},
    steps:[{title:"Generate occupancy",body:"Noise decides which windows are lit, preventing a mechanically uniform façade.",mode:"textures",node:"TEX_01",target:"#inspectorContent"},{title:"Create the mask",body:"Fold and contrast the field into clear window cells. A mask should read in black and white before color is added.",mode:"textures",node:"TEX_03",target:"#inspectorContent"},{title:"Gate emission",body:"Palette Map keeps unlit regions dark and assigns Accent only to the selected cells.",mode:"textures",node:"TEX_04",target:"#inspectorContent"},{title:"Add restrained rhythm",body:"Bind Material Mix or downstream Emission to Beat at shallow depth; the mask structure should remain stable.",mode:"textures",node:"TEX_05",target:"#inspectorContent"}]
  },
  {
    id:"texture-asphalt-grime",title:"Texture 05 · Asphalt + Grime",level:"TEXTURE WORKSHOP",duration:"6 MIN",accent:"#f1b85b",description:"Combine coarse aggregate, fine grain, coordinate warp, and grading into a grounded road material.",
    project:{name:"WORKSHOP · ASPHALT AND GRIME",bpm:98,mode:"textures",params:{color:"#111417",accent:"#8d7651",texScale:9.2,texSpeed:.02,texWarp:1.15,texContrast:2.05,texKaleido:2,texMix:.58,bloom:.12,roughness:.72}},focus:{mode:"textures",node:"TEX_02"},
    recipe:{nodeIds:["TEX_01","TEX_02","TEX_04","TEX_05"],connections:[["TEX_01","TEX_02"],["TEX_02","TEX_04"],["TEX_04","TEX_05"]],names:{TEX_01:["Stone Aggregate","COARSE + FINE"],TEX_02:["Grime Distortion","LOW SPEED"],TEX_04:["Asphalt Grade","CHARCOAL / DUST"],TEX_05:["Road Material","FULL UV"]}},
    steps:[{title:"Mix apparent scales",body:"High frequency provides grit while lower noise creates patches. The combination reads more naturally than one octave.",mode:"textures",node:"TEX_01",target:"#inspectorContent"},{title:"Break uniformity",body:"Use a moderate Domain Warp to bend stains and aggregate clusters without making the road look liquid.",mode:"textures",node:"TEX_02",target:"#inspectorContent"},{title:"Keep motion nearly zero",body:"A road material belongs to the surface. Reserve animation for rain, reflections, or deliberate transitions.",mode:"textures",node:"TEX_02",target:"#inspectorContent"},{title:"Grade for roughness",body:"Keep the palette narrow and dark. Lighting should reveal the texture instead of the texture containing painted highlights.",mode:"textures",node:"TEX_04",target:"#inspectorContent"},{title:"Inspect every corner",body:"The rectangular preview reveals edge balance and repetition that the old vignette could hide.",mode:"textures",node:"TEX_05",target:"#glCanvas"}]
  }
];

const NODE_LESSONS = [
  {title:"Masonry",kind:"Masonry",mode:"textures",track:"TEXTURE",context:"Create stable brick, tile, or block structure before adding surface variation.",params:"Course Scale sets unit size, Joint Width defines mortar, and Stagger offsets alternating rows.",connect:"Blend low-amplitude Speckles or Animated Noise after Masonry, then use Edge Wear and Palette Map.",mod:"Keep masonry structure static; animate lighting or wetness rather than the brick grid."},
  {title:"Wood Grain",kind:"Wood Grain",mode:"textures",track:"TEXTURE",context:"Build directional timber grain and plank rhythm without using object-specific image assets.",params:"Grain Scale controls growth frequency, Warp bends fibers, and Plank Seams introduces sparse manufactured joins.",connect:"Blend Rings or subtle noise into Wood Grain, use Edge Wear sparingly, then map a narrow warm palette.",mod:"Wood itself should not move. Animate roughness or reflected light at very shallow depth."},
  {title:"Fabric Weave",kind:"Fabric Weave",mode:"textures",track:"TEXTURE",context:"Represent linen, upholstery, and rugs as interlaced threads plus broad dyed variation.",params:"Thread Density sets material scale, Irregularity prevents perfect synthetic repetition, and Contrast should remain low.",connect:"Blend slow noise beneath the weave, then Palette Map; avoid Domain Warp strong enough to bend individual threads visibly.",mod:"Use no motion for ordinary cloth. A shallow event-bound contrast change can support a deliberate material transition."},
  {title:"Stone Veins",kind:"Stone Veins",mode:"textures",track:"TEXTURE",context:"Add sparse mineral veins to quartz, marble, or composite stone while retaining a quiet base.",params:"Vein Scale sets spacing, Warp bends the mineral path, and Density controls how much of the surface is veined.",connect:"Mix Stone Veins with low-contrast Speckles, then grade it into a narrow stone palette and Normal Map at low strength.",mod:"Keep the stone static; animated veins read as liquid rather than mineral."},
  {title:"Speckles",kind:"Speckles",mode:"textures",track:"TEXTURE",context:"Add pores, aggregate, droplets, pigment, or small inclusions without turning the whole texture into noise.",params:"Density controls frequency, Softness controls spot edges, and Contrast controls separation from the base.",connect:"Blend Speckles at low strength into plaster, stone, metal, glass, or ceramic before Palette Map.",mod:"For rain droplets only, very slow Speed or event-driven opacity can imply changing moisture."},
  {title:"Edge Wear",kind:"Edge Wear",mode:"textures",track:"TEXTURE",context:"Apply abrasion where a structural mask has boundaries instead of scattering wear uniformly.",params:"Width sets the edge band, Amount controls abrasion, and Breakup makes the wear intermittent.",connect:"Place Edge Wear after Masonry, Checker, Wood Grain seams, or another clean mask and before Palette Map.",mod:"Use an event to reveal wear during a transformation; keep it static for realistic architecture."},
  {title:"Particle Emitter",kind:"Particle Emitter",mode:"scene",track:"SCENE",context:"Add lightweight deterministic GPU weather, dust, mist, sparks, or ambient motes without image assets or CPU simulation.",params:"Style selects Rain, Mist, or Dust behavior. Count and Size set density, Speed and Lifetime set flow, Spread sets the emission area, Turbulence adds lateral drift, Gravity controls vertical motion, and Opacity keeps the layer integrated with the scene.",connect:"Connect Particle Emitter to the scene Output. Multiple emitters may share the output, each with independent parameters and signal bindings.",mod:"Bind Opacity or Turbulence lightly to Sine and Bar. Large beat-driven Count changes are visually noisy and can cause uneven GPU cost."},
  {title:"Spline Path",kind:"Spline Path",mode:"scene",track:"SCENE",context:"Animate a camera, mesh, or child spline along a smooth closed Catmull–Rom path with four to twelve points.",params:"Choose Point Count, edit each XYZ control point, Duration, and Phase. Use extra points for dwell shots, doorways, corners, and intentional transitions.",connect:"Connect Spline Path directly to Camera, into Spline Target or Attach to Spline, or into another Spline Path for layered motion.",mod:"Use Sine or Bar on Phase for controlled time offsets; avoid discontinuous modulation of control-point positions."},
  {title:"Spline Rotation",kind:"Spline Rotation",mode:"scene",track:"SCENE",context:"Add synchronized yaw, pitch, and roll without baking orientation into camera or mesh geometry.",params:"Yaw Turns controls horizontal rotation, Pitch controls vertical aim, Roll banks the object, and Phase offsets orientation from position.",connect:"Connect Spline Rotation to Camera or Attach to Spline alongside the position path.",mod:"A shallow Sine on Pitch produces natural look motion while Bar on Yaw can emphasize room changes."},
  {title:"Spline Target",kind:"Spline Target",mode:"scene",track:"SCENE",context:"Keep a moving camera aimed at an independently animated point on a second spline, separating dolly motion from composition.",params:"Look Ahead selects an earlier or future point on the target path, Offset XYZ corrects framing, and Strength blends tracking with an optional Spline Rotation.",connect:"Connect the look-at Spline Path into Spline Target, then connect Spline Target to Camera beside the camera movement path.",mod:"Animate Look Ahead gently with Sine for anticipatory framing, or use an Event to shift attention between staged details."},
  {title:"Mesh Anchor",kind:"Mesh Anchor",mode:"scene",track:"SCENE",context:"Make a spline local to a table, desk, room shell, or other mesh instead of world coordinates.",params:"Offset XYZ moves the anchor relative to its source mesh origin.",connect:"Connect a mesh into Mesh Anchor, then connect Mesh Anchor into Spline Path. The path now follows that mesh coordinate frame.",mod:"Animate anchor offsets only for deliberate rig changes; use the child spline for ordinary motion."},
  {title:"Attach to Spline",kind:"Attach to Spline",mode:"scene",track:"SCENE",context:"Bind a scene object to position and rotation splines while keeping the original mesh node independently editable.",params:"Offset XYZ corrects placement, Start changes phase, Speed changes travel direction/rate, and Orient blends spline rotation.",connect:"Connect the mesh, Spline Path, and optional Spline Rotation into Attach to Spline, then route the attachment to the scene material.",mod:"Bind Speed to Bar for phrase changes or Start to an Event for a synchronized launch."},
  {title:"Primitive",kind:"Primitive",mode:"scene",track:"SCENE",context:"Start with a reusable low-level signed-distance shape rather than a specific furniture or architectural object.",params:"Choose Sphere, Cylinder, Cone, Pyramid, Capsule, boxes, prisms, Plane, Disc, Torus, Ellipsoid, Wedge, Triangular Prism, or Tube; then establish Scale and Detail while watching the silhouette.",connect:"Connect Primitive into Transform, repetition, Boolean composition, and Bevel to construct named objects from visible graph stages.",mod:"Bind Shape to an Act Event for deliberate form changes, or bind Scale lightly to Envelope for impact."},
  {title:"Text",kind:"Text",mode:"scene",track:"SCENE",context:"Layer editable typography over the rendered WebGL scene for titles, labels, and narrative chapters.",params:"Set content, color, size, screen position, rotation, and wave amount in the inspector.",connect:"Connect Text to the scene Output; it renders as an overlay rather than geometry.",mod:"Use Bar for slow rotation or Sine for wave motion; keep title movement restrained."},
  {title:"Grid Array",kind:"Grid Array",mode:"scene",track:"SCENE",context:"Repeat one incoming form into architectural rows, fields, or radial structures.",params:"Columns controls repetition, Spacing controls separation, and Offset shifts the pattern.",connect:"Place Grid Array after a generator or Multiply and before deformation or material.",mod:"Bind Offset to Bar for deliberate pattern travel synchronized to musical phrases."},
  {title:"Fractal",kind:"Fractal",mode:"scene",track:"SCENE",context:"Introduce recursive detail when a clean primitive needs organic or crystalline complexity.",params:"Raise Iterations gradually, then balance Complexity against Scale to preserve readability.",connect:"Place Fractal after a Primitive and before Multiply or the main deformation chain.",mod:"Envelope-bound Complexity creates growth on hits without constant visual noise."},
  {title:"Multiply",kind:"Multiply",mode:"scene",track:"SCENE",context:"Create coordinated copies for swarms, petals, orbitals, and repeated mechanical forms.",params:"Copies sets density, Spread defines the formation, and Spin rotates the copies.",connect:"Feed it geometry from Primitive or Fractal, then continue into Array, Twist, or Material.",mod:"Use Half-beat on Spread for a breathing formation and Bar on Spin for slow evolution."},
  {title:"Transform",kind:"Transform",mode:"scene",track:"SCENE",context:"Correct composition and orientation without changing the source generator.",params:"Set Scale first, then Rotation and Depth to place the object in the camera composition.",connect:"Insert Transform anywhere in a geometry chain, commonly immediately before Output-facing material.",mod:"Sine on Rotation creates a stable turntable; avoid deep Beat modulation on Scale."},
  {title:"Twist",kind:"Twist",mode:"scene",track:"SCENE",context:"Turn rigid geometry into spirals, ribbons, and torsioned architectural forms.",params:"Amount sets torsion, Scale controls the affected form, and Pulse adds rhythmic deformation.",connect:"Place Twist after the main geometry construction and before Material.",mod:"Bind Amount to Half-beat at low depth so the object flexes rather than flickers."},
  {title:"Displace",kind:"Displace",mode:"scene",track:"SCENE",context:"Push a surface with procedural noise to make liquid, terrain, smoke-like, or damaged forms.",params:"Amount controls strength, Frequency controls feature size, and Speed animates the field.",connect:"Use after a stable base shape; follow it with Mirror or Material for a controlled finish.",mod:"Envelope on Amount produces impact ripples; Sine on Speed creates continuous flow."},
  {title:"Mirror",kind:"Mirror",mode:"scene",track:"SCENE",context:"Fold asymmetric geometry into deliberate bilateral or radial symmetry.",params:"Axes chooses the number of folds and Angle rotates the symmetry plane.",connect:"Place Mirror after deformation when you want the deformation repeated symmetrically.",mod:"Slow Sine modulation on Angle creates evolving kaleidoscopic geometry."},
  {title:"Boolean Union",kind:"Boolean Union",mode:"scene",track:"SCENE",context:"Join an incoming mesh with a second signed-distance volume to construct a larger silhouette.",params:"Offset controls how far the tool volume sits from the source; Scale keeps the combined result framed.",connect:"Connect Primitive into Boolean Union, then continue into Bevel, a material, and Output.",mod:"Bind Offset lightly to Sine to demonstrate assembly without separating the volumes completely."},
  {title:"Boolean Subtract",kind:"Boolean Subtract",mode:"scene",track:"SCENE",context:"Carve a clean negative volume from a solid mesh for arches, sockets, vents, and mechanical cavities.",params:"Cutter Size controls the removed volume and Offset moves the cut through the source.",connect:"Place after a closed Primitive and before Bevel or material shading.",mod:"Use an Event binding on Offset to animate a reveal of the internal cavity."},
  {title:"Smooth Union",kind:"Smooth Union",mode:"scene",track:"SCENE",context:"Blend two volumes into one continuous organic surface instead of leaving a hard Boolean seam.",params:"Smoothness controls the blend radius and Offset controls the relationship between the volumes.",connect:"Use after Primitive when building metaballs, creatures, roots, or soft industrial forms.",mod:"Envelope-bound Smoothness makes separate pieces fuse together on musical impacts."},
  {title:"Bevel",kind:"Bevel",mode:"scene",track:"SCENE",context:"Round hard signed-distance edges so highlights describe the form more naturally.",params:"Radius controls edge width; inspect the silhouette and avoid rounding away small features.",connect:"Place after Boolean composition and before material shading.",mod:"A shallow Envelope on Radius can emphasize impacts without changing the main silhouette."},
  {title:"Bend",kind:"Bend",mode:"scene",track:"SCENE",context:"Curve a straight mesh continuously along its vertical axis for arches, cables, and swept structures.",params:"Amount controls curvature while Scale keeps the result inside the camera.",connect:"Place after the main construction step and before repetition or material.",mod:"Bind Amount to Sine for a slow flex, or to Envelope for a brief impact bend."},
  {title:"Taper",kind:"Taper",mode:"scene",track:"SCENE",context:"Change cross-section progressively along height to build towers, spikes, trunks, and manufactured draft angles.",params:"Amount controls widening or narrowing and Axis Bias shifts the deformation orientation.",connect:"Use after Primitive or Extrude and before Bevel or material.",mod:"A slow Bar binding on Amount creates readable growth across musical phrases."},
  {title:"Extrude",kind:"Extrude",mode:"scene",track:"SCENE",context:"Turn a flat procedural profile into a solid mesh with controllable depth.",params:"Depth controls thickness and Bevel softens the front and rear edges.",connect:"Treat the incoming Primitive as the profile source, then route Extrude into Bend, Bevel, or material.",mod:"Bind Depth to Envelope for punchy type-like or panel-like construction."},
  {title:"Radial Repeat",kind:"Radial Repeat",mode:"scene",track:"SCENE",context:"Arrange copies around a circular formation for rotors, petals, arches, and mechanical rings.",params:"Count controls density, Radius sets placement, and Spin rotates the complete formation.",connect:"Place after a compact source shape and before deformation or material.",mod:"Bind Spin to Bar for steady phrase motion and Radius lightly to Envelope for breathing."},
  {title:"Iridescent",kind:"Iridescent",mode:"scene",track:"MATERIAL",context:"Finish geometry with reflective color-shifting highlights for chrome and interference looks.",params:"Metallic sets reflectivity, Roughness broadens highlights, Pulse adds reactive energy, and Exposure balances brightness.",connect:"Connect the final geometry and optional Texture Output into Iridescent, then route it to Output.",mod:"Use Envelope on Roughness and Beat on Pulse for musical highlights with stable base shading."},
  {title:"Emission",kind:"Emission",mode:"scene",track:"MATERIAL",context:"Make surfaces self-lit for neon, energy cores, holograms, and luminous story beats.",params:"Glow spreads light, Intensity controls the base emission, and Pulse adds rhythmic brightness.",connect:"Place after geometry and before Output; pair it with Bloom in the Post FX graph.",mod:"Beat on Glow creates flashes; Half-beat on Intensity gives a slower breathing light."},
  {title:"Glass",kind:"Glass",mode:"scene",track:"MATERIAL",context:"Use a glossy translucent treatment for shells, lenses, crystals, and liquid membranes.",params:"Lower Roughness for a clean lens, increase Refraction for distortion, then rebalance Exposure.",connect:"Feed clean or lightly displaced geometry into Glass and send it directly to Output.",mod:"Sine on Refraction gives subtle liquid motion; avoid large Beat jumps that break continuity."},
  {title:"Normal Map",kind:"Normal Map",mode:"scene",track:"MATERIAL",context:"Convert procedural texture contrast into small surface detail without changing the silhouette.",params:"Strength sets apparent depth, Scale sets detail size, and Mix controls material influence.",connect:"Route Texture Output into Normal Map, then combine it with a scene material.",mod:"Envelope on Strength adds per-hit surface energy while keeping the geometry inexpensive."},
  {title:"Beat Signal",kind:"Beat",mode:"scene",track:"SIGNAL",context:"Use the transport BPM as a shared clock for synchronized visual and audio movement.",params:"Amplitude controls the resulting pulse and Rate changes how strongly the clock affects bound values.",connect:"Beat is bound through inspector MOD controls rather than requiring a visual wire for every property.",mod:"Start with Beat on material Pulse or Bloom at 10–25% depth, then reuse it across graphs."},
  {title:"Sine Signal",kind:"Sine",mode:"scene",track:"SIGNAL",context:"Create smooth cyclic motion for cameras, rotations, texture flow, and slow color changes.",params:"Amplitude sets travel, Frequency sets speed, and Phase offsets multiple motions.",connect:"Bind Sine from a target property's MOD selector; use separate depths to coordinate several nodes.",mod:"Sine is ideal for camera yaw and texture speed because it has no discontinuities."},
  {title:"Envelope Signal",kind:"Envelope",mode:"scene",track:"SIGNAL",context:"Turn each beat or event into a fast attack followed by an adjustable decay curve.",params:"Attack controls onset, Decay controls release length, and Amount controls peak influence.",connect:"Bind Envelope to scale, displacement, bloom, roughness, or filter cutoff.",mod:"Use positive depth for punches and negative depth for ducking effects on the same beat."},
  {title:"Noise Signal",kind:"Noise",mode:"scene",track:"SIGNAL",context:"Add controlled unpredictability for glitches, flicker, camera shake, and evolving textures.",params:"Amount sets deviation and Frequency controls how often the random value changes.",connect:"Select Noise in any numeric property's MOD row; no explicit graph wire is required.",mod:"Keep depth below 10% for organic variation; reserve high depth for intentional glitch sections."},
  {title:"Animated Noise",kind:"Animated Noise",mode:"textures",track:"TEXTURE",context:"Begin a texture graph with time-varying procedural values generated entirely on the GPU.",params:"Frequency sets detail size, Speed advances the field, and Contrast shapes the value range.",connect:"Start the texture chain here, then route into Domain Warp, Kaleidoscope, or Palette Map.",mod:"Bar on Frequency and Sine on Speed produce movement that evolves without boiling."},
  {title:"Checker",kind:"Checker",mode:"textures",track:"TEXTURE",context:"Create a generic tiled binary field for masonry, fabric crossings, cabinets, floors, and manufactured masks.",params:"Scale sets tile size, Softness controls edges, and Contrast separates the two values.",connect:"Blend Checker with Noise or Stripes before Palette Map and Texture Output.",mod:"Animate Scale only for deliberate transitions; architectural checker patterns should normally remain fixed."},
  {title:"Stripes",kind:"Stripes",mode:"textures",track:"TEXTURE",context:"Create directional bands for fibers, brushed metal, wood grain, seams, and layered construction.",params:"Scale controls band frequency, Angle changes direction, and Contrast controls edge definition.",connect:"Blend Stripes with Noise to break perfect repetition, then color the result through Palette Map.",mod:"Use a shallow Sine on Angle for effects; keep physical surface fibers static."},
  {title:"Voronoi",kind:"Voronoi",mode:"textures",track:"TEXTURE",context:"Create generic cellular distances for stone aggregate, plaster pores, droplets, leaf cells, and cracked variation.",params:"Cell Scale controls feature size, Jitter breaks regularity, and Contrast isolates cell edges or centers.",connect:"Combine Voronoi with Noise in Texture Blend before grading and output.",mod:"A small Envelope on Jitter can animate growth; realistic materials usually use zero-speed cells."},
  {title:"Gradient",kind:"Gradient",mode:"textures",track:"TEXTURE",context:"Create a controlled directional mask for wear, height variation, glass falloff, and material transitions.",params:"Scale controls ramp width, Angle sets direction, and Offset moves the transition.",connect:"Feed Gradient into Texture Blend as a mask or tonal layer before Palette Map.",mod:"Bind Offset to an Event for reveals or use Sine for slow moving light-like masks."},
  {title:"Rings",kind:"Rings",mode:"textures",track:"TEXTURE",context:"Create concentric bands for timber growth, thrown ceramic grooves, machining, and circular details.",params:"Frequency controls ring density, Warp introduces natural deviation, and Contrast sharpens bands.",connect:"Blend Rings with Noise so repeated bands acquire believable material irregularity.",mod:"Use very shallow Noise on Warp for organic drift; physical rings should not visibly flow."},
  {title:"Texture Blend",kind:"Texture Blend",mode:"textures",track:"TEXTURE",context:"Combine two generic primitive histories into a reusable material signal instead of relying on a semantic material generator.",params:"Mix balances both inputs, Contrast shapes their result, and Bias shifts the value distribution.",connect:"Connect two texture primitives into Texture Blend, then route it through Palette Map to a named Texture Output.",mod:"Animate Mix with an Event to transition between surface states or keep it fixed for authored materials."},
  {title:"Domain Warp",kind:"Domain Warp",mode:"textures",track:"TEXTURE",context:"Distort texture coordinates with another field to create liquid curls and turbulent flow.",params:"Amount sets distortion, Frequency sets warp scale, and Speed controls advection.",connect:"Place after Animated Noise and before folding or palette operations.",mod:"Envelope on Amount creates rhythmic ripples while a slow Sine keeps the flow alive."},
  {title:"Kaleidoscope",kind:"Kaleidoscope",mode:"textures",track:"TEXTURE",context:"Fold an incoming texture into radial symmetry for rosettes, tunnels, and graphic patterns.",params:"Segments controls symmetry, Rotation animates the fold, and Warp softens rigid repetition.",connect:"Use after Noise or Domain Warp and before Palette Map.",mod:"Bar on Rotation creates readable phrase-level movement; Event on Segments makes sharp transitions."},
  {title:"Palette Map",kind:"Palette Map",mode:"textures",track:"TEXTURE",context:"Translate monochrome procedural values into the project's Base and Accent color system.",params:"Contrast sets separation, Material Mix sets influence, and Speed shifts animated mapping.",connect:"Place near the end of the texture chain, immediately before Texture Output.",mod:"Beat on Material Mix lets the texture flash through while preserving the base material."},
  {title:"Texture Output",kind:"Texture Output",mode:"textures",track:"TEXTURE",context:"Publish the final GPU texture so scene materials and Normal Map can consume it.",params:"Material Mix controls visibility and Scale adjusts how the result maps onto geometry.",connect:"Texture Output terminates the texture graph; connect its conceptual output into scene materials.",mod:"Use a shallow Envelope on Material Mix for synchronized reveal effects."},
  {title:"Drum Machine",kind:"Drum Machine",mode:"audio",track:"AUDIO",context:"Generate kick, snare, and hi-hat transients from the shared transport clock.",params:"Decay controls transient length and Drive increases aggression and harmonic density.",connect:"Feed it the Beat Clock, then route its output through Lowpass or directly to Audio Output.",mod:"Bar on Drive changes intensity by phrase; keep Decay stable enough to preserve the groove."},
  {title:"Noise Percussion",kind:"Noise Percussion",mode:"audio",track:"AUDIO",context:"Synthesize brushes, shakers, rain and metallic percussion from filtered noise instead of external samples.",params:"Tone moves the filter from dark brushes to bright shakers while Decay controls the tail.",connect:"Feed it Beat, then route it to Mixer or through Reverb for an environmental percussion bed.",mod:"Use Bar on Tone to brighten later sections and a shallow Envelope on Decay for breathing accents."},
  {title:"Bass Synth",kind:"Bass Synth",mode:"audio",track:"AUDIO",context:"Create a sequenced sawtooth bass voice that anchors both rhythm and visual modulation.",params:"Cutoff sets brightness, Decay sets note length, and Drive controls resonance and edge.",connect:"Connect Beat Clock into Bass Synth, then combine it with drums before Lowpass or Delay.",mod:"Envelope on Cutoff produces classic rhythmic filter movement synchronized to each note."},
  {title:"Poly Synth",kind:"Poly Synth",mode:"audio",track:"AUDIO",context:"Build warm chord stabs from multiple detuned oscillators and a shared filter envelope.",params:"Attack softens the onset, Release controls chord length, and Detune widens the voicing.",connect:"Feed chord events or Beat into Poly Synth, then route through Chorus and Reverb before Mixer.",mod:"Bind Detune lightly to Sine for drift and Release to Bar for longer harmony in later phrases."},
  {title:"Pad Synth",kind:"Pad Synth",mode:"audio",track:"AUDIO",context:"Layer slow triangle voices into a sustained harmonic bed that can carry an entire visual scene.",params:"Attack and Release determine overlap while Level preserves headroom under drums and melody.",connect:"Trigger one chord per bar, then route through Chorus, Reverb, Mixer and Audio Output.",mod:"Use a slow Sine on Level or filter cutoff; avoid Beat modulation that makes sustained pads pump abruptly."},
  {title:"Arpeggiator",kind:"Arpeggiator",mode:"audio",track:"AUDIO",context:"Turn each chord into a synchronized rising pattern spanning one to three octaves.",params:"Rate selects rhythmic density and Octaves controls melodic range.",connect:"Feed it Beat and a harmonic source, then send its native voice through Delay or Reverb.",mod:"Use Bar on Rate for a gradual density build and Event on Octaves for a clear section lift."},
  {title:"Lowpass",kind:"Lowpass",mode:"audio",track:"AUDIO",context:"Shape the combined soundtrack by removing high frequencies and emphasizing the cutoff region.",params:"Cutoff sets brightness and Resonance sharpens frequencies around that cutoff.",connect:"Place after Drum Machine and Bass Synth, before Delay and Audio Output.",mod:"Sine on Cutoff creates long sweeps; Envelope creates per-hit filter plucks."},
  {title:"Chorus",kind:"Chorus",mode:"audio",track:"AUDIO",context:"Create stereo-like ensemble width with a slowly modulated short WebAudio delay.",params:"Depth controls wet level and Rate controls the movement speed.",connect:"Place after Poly Synth or Pad Synth and before Reverb or Mixer.",mod:"Use Sine on Depth at low range for organic width without obvious pitch wobble."},
  {title:"Delay",kind:"Delay",mode:"audio",track:"AUDIO",context:"Add rhythmic echoes that turn sparse notes into space and forward motion.",params:"Feedback controls repeat count and Mix balances dry signal against echoes.",connect:"Place after filtering and before Audio Output; avoid feeding an already loud master into it.",mod:"Use Act Event on Mix to introduce echoes only at scene transitions."},
  {title:"Reverb",kind:"Reverb",mode:"audio",track:"AUDIO",context:"Place connected voices inside a generated convolution room without downloading an impulse response.",params:"Room Mix controls wet level and Decay determines perceived room size.",connect:"Combine melodic effects into Reverb, then route it into Mixer and Audio Output.",mod:"Use Bar on Room Mix to open the space during transitions while keeping bass on a dry branch."},
  {title:"Mixer",kind:"Mixer",mode:"audio",track:"AUDIO",context:"Collect drums, bass, harmony and effect returns into one controlled pre-master stage.",params:"Pre-master sets headroom and Drive adds controlled density before the final output compressor.",connect:"Connect every audible branch here, then connect Mixer directly to Audio Output.",mod:"Use shallow negative Envelope modulation on Pre-master for sidechain-style ducking."},
  {title:"Audio Output",kind:"Audio Output",mode:"audio",track:"AUDIO",context:"Control the final WebAudio level delivered to the browser speakers.",params:"Volume is the last gain stage; leave headroom for overlapping drums, bass, pads, and delay.",connect:"Every audible branch must ultimately reach Audio Output.",mod:"Use gentle negative Envelope modulation for sidechain-style ducking; avoid full-range modulation."},
  {title:"Scene Input",kind:"Scene Input",mode:"post",track:"POST FX",context:"Bring the completed 3D render into the post-processing workspace as HDR color.",params:"Exposure sets the starting brightness before bloom, grading, grain, and vignette.",connect:"Scene Input must be the first node in the Post FX chain.",mod:"Keep modulation subtle here; large changes affect every downstream effect."},
  {title:"Bloom",kind:"Bloom",mode:"post",track:"POST FX",context:"Spread energy from bright pixels to create glow, atmosphere, and musical flashes.",params:"Intensity sets spread strength and Exposure controls which highlights feed the effect.",connect:"Place after Scene Input or Chromatic and before final grading and vignette.",mod:"Beat on Intensity works well at 10–20% depth; too much bloom destroys silhouette contrast."},
  {title:"Chromatic",kind:"Chromatic",mode:"post",track:"POST FX",context:"Separate color channels near edges for lens energy, glitches, and transition accents.",params:"Amount controls separation and Speed animates the distortion.",connect:"Place early in the Post FX chain so later Bloom can react to the separated highlights.",mod:"Trigger Amount from Act Event rather than running a strong split continuously."},
  {title:"Color Grade",kind:"Color Grade",mode:"post",track:"POST FX",context:"Balance exposure and contrast after lighting so every scene shares a deliberate finish.",params:"Exposure controls overall brightness and Contrast sets tonal separation.",connect:"Place after Bloom and Chromatic but before Grain, Vignette, and Final Image.",mod:"Use slow Bar modulation for chapter-to-chapter tonal change, not rapid Beat flicker."},
  {title:"Vignette",kind:"Vignette",mode:"post",track:"POST FX",context:"Darken the perimeter to focus attention and contain bright procedural imagery.",params:"Amount sets edge darkness and Exposure compensates for perceived brightness loss.",connect:"Place near the end of the post chain, before Final Image.",mod:"A shallow Envelope can make the frame breathe; strong modulation feels like unwanted flashing."},
  {title:"Film Grain",kind:"Film Grain",mode:"post",track:"POST FX",context:"Add high-frequency texture that unifies gradients and gives digital scenes a physical surface.",params:"Amount sets grain visibility and Exposure balances the final image.",connect:"Place after grading and before Vignette or Final Image.",mod:"Noise modulation at very low depth prevents a static-looking grain pattern."},
  {title:"Camera",kind:"Camera",mode:"scene",track:"SCENE",context:"Compose the procedural world with independently controlled position and aim.",params:"Distance frames the subject, Yaw and Pitch provide manual control, a Spline Path drives position, and Spline Target drives look-at composition.",connect:"Connect movement Spline Path and optional Spline Target into Camera, then connect Camera to scene Output.",mod:"Use a shallow Sine on manual Pitch or on Spline Target Look Ahead for smooth anticipatory cinematography."},
  {title:"Scene Output",kind:"Output",mode:"scene",track:"SCENE",context:"Combine scene geometry, material, camera, text, and automation into the final rendered frame.",params:"Show Automation blends scripted acts; Exposure and Bloom provide final scene-level trim.",connect:"Route the final material, Camera, and every Text operator into Output.",mod:"Act Event on Exposure can emphasize transitions, but keep the base output stable."}
];

const EXISTING_NODE_IDS={
  "scene:Primitive":"GEO_02","scene:Grid Array":"ARR_05","scene:Fractal":"FRA_03","scene:Multiply":"MUL_04","scene:Twist":"MOD_03","scene:Iridescent":"MAT_04","scene:Beat":"SIG_01","scene:Camera":"CAM_06","scene:Output":"OUT_07",
  "textures:Animated Noise":"TEX_01","textures:Domain Warp":"TEX_02","textures:Kaleidoscope":"TEX_03","textures:Palette Map":"TEX_04","textures:Texture Output":"TEX_05",
  "post:Scene Input":"POST_01","post:Bloom":"POST_02","post:Color Grade":"POST_03","post:Vignette":"POST_04",
  "audio:Drum Machine":"AUDIO_02","audio:Bass Synth":"AUDIO_03","audio:Lowpass":"AUDIO_04","audio:Audio Output":"AUDIO_05"
};
const TRACK_COLORS={SCENE:"#5da7ff",MATERIAL:"#ff6d42",SIGNAL:"#55d887",TEXTURE:"#25c9cd",AUDIO:"#55d887","POST FX":"#9b7bff"};
const MODE_PARAMS={scene:{color:"#ff6347",accent:"#61e9ff",twist:1.1,bloom:.64,pulse:.54},textures:{color:"#ff426d",accent:"#25d9d3",texScale:5.4,texSpeed:.48,texWarp:1.85,texContrast:1.72,texKaleido:7,texMix:.86},post:{color:"#ff7a3d",accent:"#6c4dff",bloom:.9,vignette:.3,exposure:1.05},audio:{color:"#ff365f",accent:"#36ffd1",pulse:.76,audioCutoff:820,audioDecay:.4,audioDrive:.65}};
const slug=value=>value.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"");
const ADVANCED_NODE_TUTORIALS=NODE_LESSONS.map((lesson,index)=>{
  const key=`${lesson.mode}:${lesson.kind}`,node=EXISTING_NODE_IDS[key]||`TUT_${String(index+1).padStart(2,"0")}`,accent=TRACK_COLORS[lesson.track]||"#ff6d42";
  return {id:`advanced-${slug(lesson.title)}`,title:lesson.title,level:`ADVANCED · ${lesson.track}`,track:lesson.track,simple:true,duration:"3 MIN",accent,description:lesson.context,
    project:{name:`ADVANCED · ${lesson.title.toUpperCase()}`,bpm:lesson.mode==="audio"?118:128,mode:lesson.mode,params:{...MODE_PARAMS[lesson.mode]}},
    focus:{node,kind:lesson.kind,mode:lesson.mode,template:EXISTING_NODE_IDS[key]?null:{id:node,name:lesson.title,type:`${lesson.track} OPERATOR`,kind:lesson.kind,x:355,y:54,color:accent,value:"LESSON",enabled:true}},
    steps:[
      {title:`${lesson.title} in context`,body:lesson.context,mode:lesson.mode,node,target:"#graphCanvas"},
      {title:"Place it in the graph",body:lesson.connect,mode:lesson.mode,node,target:`.node[data-id="${node}"]`},
      {title:"Tune the important controls",body:lesson.params,mode:lesson.mode,node,target:"#inspectorContent"},
      {title:"Read the signal flow",body:`Follow the ports and wires around ${lesson.title}. ${lesson.connect}`,mode:lesson.mode,node,target:"#graphCanvas"},
      {title:"Animate it deliberately",body:lesson.mod,mode:lesson.mode,node,target:"#inspectorContent"}
    ]};
});

const WZ4_TUTORIALS=WZ4_OPERATORS.map((spec,index)=>{
  const runtime=compatRuntimeFor(spec),mode=compatModeFor(spec),node=`WZT_${String(index+1).padStart(3,"0")}`,track=`WZ4 · ${spec.family}`,accent=COMPAT_COLORS[spec.family],signature=`${spec.output} ${spec.symbol}(${spec.inputs||""})`;
  return {id:`wz4-${slug(spec.id)}`,title:`${spec.name} · ${spec.module}`,level:"WZ4 WEBGL EQUIVALENT",track,simple:true,duration:"3 MIN",accent,description:runtime.summary,
    project:{name:`WZ4 · ${spec.name.toUpperCase()}`,bpm:128,mode,params:{...MODE_PARAMS[mode]}},
    focus:{node,kind:spec.symbol,mode,template:{id:node,name:spec.name,type:`${spec.output} OPERATOR`,kind:spec.symbol,x:355,y:54,color:accent,value:"WEBGL",enabled:true,params:{...runtime.params},compat:{...spec},compatRuntime:runtime}},
    steps:[
      {title:`${spec.name} browser equivalent`,body:`The original declaration is ${signature}. This session uses a deterministic ${spec.family} WebGL substitute rather than claiming DirectX binary parity.`,mode,node,target:"#graphCanvas"},
      {title:"Use it in context",body:runtime.usage,mode,node,target:`.node[data-id="${node}"]`},
      {title:"Tune the live controls",body:"Intensity controls the strength, Rate controls motion, Scale changes spatial frequency or spread, and Mix blends the equivalent with the incoming graph.",mode,node,target:"#inspectorContent"},
      {title:"Follow the declared I/O",body:`Declared input: ${spec.inputs||"none"}. Declared output: ${spec.output}. Connect compatible branches left-to-right as you would in Werkkzeug4.`,mode,node,target:"#graphCanvas"},
      {title:"Animate the substitute",body:`Bind Intensity or Mix to Beat/Envelope for rhythmic changes; bind Rate or Scale to Sine/Bar for continuous motion. The seed ${runtime.seed.toFixed(3)} keeps this operator visually distinct.`,mode,node,target:"#inspectorContent"}
    ]};
});

export const TUTORIALS=[...GUIDED_TUTORIALS,...TEXTURE_WORKSHOPS,...ADVANCED_NODE_TUTORIALS,...WZ4_TUTORIALS];
